msgid ""
msgstr ""
"Project-Id-Version: duplicity\n"
"Report-Msgid-Bugs-To: Kenneth Loafman <kenneth@loafman.com>\n"
"POT-Creation-Date: 2023-12-27 10:21-0600\n"
"PO-Revision-Date: 2023-12-27 17:28\n"
"Last-Translator: \n"
"Language-Team: Spanish, United States\n"
"Language: es_US\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
"X-Crowdin-Project: duplicity\n"
"X-Crowdin-Project-ID: 539508\n"
"X-Crowdin-Language: es-US\n"
"X-Crowdin-File: /main/po/duplicity.pot\n"
"X-Crowdin-File-ID: 6\n"

#: ../bin/duplicity:76
msgid "INT intercepted...exiting."
msgstr "INT interceptado... saliendo."

#: ../bin/duplicity:84
#, python-format
msgid "GPG error detail: %s"
msgstr "Detalle de error GPG: %s"

#: ../bin/duplicity:91
#, python-format
msgid "User error detail: %s"
msgstr "Detalle de error del usuario: %s"

#: ../bin/duplicity:98
#, python-format
msgid "Backend error detail: %s"
msgstr "Detalle de error del motor: %s"

#: ../duplicity/tempdir.py:157
#, python-format
msgid "Using temporary directory %s"
msgstr "Utilizando directorio temporal %s"

#: ../duplicity/tempdir.py:201
#, python-format
msgid "Registering (mktemp) temporary file %s"
msgstr "Registrando archivo temporal (mktemp) %s"

#: ../duplicity/tempdir.py:227
#, python-format
msgid "Registering (mkstemp) temporary file %s"
msgstr "Registrando archivo temporal (mkstemp) %s"

#: ../duplicity/tempdir.py:259
#, python-format
msgid "Forgetting temporary file %s"
msgstr "Olvidando el archivo temporal %s"

#: ../duplicity/tempdir.py:262
#, python-format
msgid "Attempt to forget unknown tempfile %s - this is probably a bug."
msgstr "Intentando olvidar un archivo temporal desconocido %s. Esto es posiblemente un error."

#: ../duplicity/tempdir.py:281
#, python-format
msgid "Removing still remembered temporary file %s"
msgstr "Eliminar archivo temporal todavía recordado %s"

#: ../duplicity/tempdir.py:284
#, python-format
msgid "Cleanup of temporary file %s failed"
msgstr "La limpieza del archivo temporal %s falló"

#: ../duplicity/tempdir.py:290
#, python-format
msgid "Cleanup of temporary directory %s failed - this is probably a bug."
msgstr "La limpieza del directorio temporal %s falló. Esto posiblemente sea un error."

#: ../duplicity/backend.py:92
#, python-format
msgid "Import of %s %s"
msgstr "Importación de %s %s"

#: ../duplicity/backend.py:197
#, python-format
msgid "Could not initialize backend: %s"
msgstr "No se pudo inicializar el motor: %s"

#: ../duplicity/backend.py:388
#, python-format
msgid "Backtrace of previous error: %s"
msgstr "Volcado de pila del error anterior: %s"

#: ../duplicity/backend.py:407
#, python-format
msgid "Giving up after %s attempts. %s: %s"
msgstr "Desistiendo tras %s intentos. %s: %s"

#: ../duplicity/backend.py:413
#, python-format
msgid "Attempt of %s Nr. %s failed. %s: %s"
msgstr ""

#: ../duplicity/backend.py:512
#, python-format
msgid "Reading results of '%s'"
msgstr "Leyendo resultados de «%s»"

#: ../duplicity/backend.py:539
#, python-format
msgid "Writing %s"
msgstr "Escribiendo %s"

#: ../duplicity/backend.py:580
#, python-format
msgid "File %s not found locally after get from backend"
msgstr "archivo %s no encontrado localmente tras obtenerlo del servidor"

#: ../duplicity/manifest.py:95
#, python-format
msgid "Fatal Error: Backup source host has changed.\n"
"Current hostname: %s\n"
"Previous hostname: %s"
msgstr "Error fatal: el anfitrión de origen del respaldo ha cambiado.\n"
"Anfitrión actual: %s\n"
"Anfitrión anterior: %s"

#: ../duplicity/manifest.py:102
msgid "Fatal Error: Backup source directory has changed.\n"
msgstr ""

#: ../duplicity/manifest.py:115
msgid "Aborting because you may have accidentally tried to backup two different data sets to the same remote location, or using the same archive directory.  If this is not a mistake, use the --allow-source-mismatch switch to avoid seeing this message"
msgstr "Abortar porque puede haber intentado dos conjuntos de datos distintos en la misma ubicación remota por error, o utilizado el mismo directorio de archivo. Sí no es un error, use --allow-source-mismatch para no ver este mensaje"

#: ../duplicity/manifest.py:221
#, python-format
msgid "Found manifest volume %s"
msgstr "Volumen manifest encontrado %s"

#: ../duplicity/manifest.py:228
#, python-format
msgid "Found %s volumes in manifest"
msgstr "Encontrados %s volúmenes en el manifiesto"

#: ../duplicity/manifest.py:249
msgid "Manifest file '{self.fh.base if self.fh else ''}' is corrupt: "
msgstr ""

#: ../duplicity/manifest.py:268
msgid "Manifests not equal because different volume numbers"
msgstr "Los manifiestos no son iguales debido a los diferentes números de volumen"

#: ../duplicity/manifest.py:273
msgid "Manifests not equal because volume lists differ"
msgstr "Los manifiestos no son iguales porque las listas de volúmenes difieren"

#: ../duplicity/manifest.py:277
msgid "Manifests not equal because hosts or directories differ"
msgstr "Los manifiestos no son iguales porque los anfitriones o directorios no coinciden"

#: ../duplicity/manifest.py:438
msgid "Warning, found extra Volume identifier"
msgstr "Aviso, se encontró un identificador de volumen extra"

#: ../duplicity/manifest.py:464
msgid "Other is not VolumeInfo"
msgstr "Otro no es VolumeInfo"

#: ../duplicity/manifest.py:467
msgid "Volume numbers don't match"
msgstr "Los números de volúmenes no coinciden"

#: ../duplicity/manifest.py:470
msgid "start_indicies don't match"
msgstr "start_indicies no coinciden"

#: ../duplicity/manifest.py:473
msgid "end_index don't match"
msgstr "end_index no coinciden"

#: ../duplicity/manifest.py:478
msgid "Hashes don't match"
msgstr "Hashes no coinciden"

#: ../duplicity/util.py:105 ../duplicity/dup_main.py:906
#, python-format
msgid "IGNORED_ERROR: Warning: ignoring error as requested: %s: %s"
msgstr "IGNORED_ERROR: Aviso: ignorando error tal como se pidió: %s: %s"

#: ../duplicity/util.py:170
#, python-format
msgid "Releasing lockfile %s"
msgstr "Publicando fichero de candado %s"

#: ../duplicity/backends/pydrivebackend.py:203
#, python-format
msgid "PyDrive backend: multiple files called '%s'."
msgstr "PyDrive backend: se llamaron múltiples archivos «%s»."

#: ../duplicity/backends/multibackend.py:100
#, python-format
msgid "MultiBackend: Could not parse query string %s: %s "
msgstr "MultBackend: no se pudo analizar la cadena de consulta %s: %s "

#: ../duplicity/backends/multibackend.py:110
#, python-format
msgid "MultiBackend: Invalid query string %s: more than one value for %s"
msgstr "MultBackend: cadena de consulta no válida %s: más de un valor para %s"

#: ../duplicity/backends/multibackend.py:116
#, python-format
msgid "MultiBackend: Invalid query string %s: unknown parameter %s"
msgstr "MultBackend: cadena de consulta no válida %s: parámetro desconocido %s"

#: ../duplicity/backends/multibackend.py:167
#: ../duplicity/backends/multibackend.py:174
#, python-format
msgid "MultiBackend: illegal value for %s: %s"
msgstr "MultBackend: valor no permitido para %s: %s"

#: ../duplicity/backends/multibackend.py:186
#, python-format
msgid "MultiBackend: Url %s"
msgstr ""

#: ../duplicity/backends/multibackend.py:189
#, python-format
msgid "MultiBackend: Could not load config file %s: %s "
msgstr "MultBackend: no se pudo cargar el archivo de configuración %s: %s "

#: ../duplicity/backends/multibackend.py:196
#, python-format
msgid "MultiBackend: use store %s"
msgstr "MultiBackend: usar almacén %s"

#: ../duplicity/backends/multibackend.py:200
#, python-format
msgid "MultiBackend: set env %s = %s"
msgstr ""

#: ../duplicity/backends/multibackend.py:214
#, python-format
msgid "Multibackend: register affinity for prefix %s"
msgstr ""

#: ../duplicity/backends/multibackend.py:257
#, python-format
msgid "MultiBackend: _put: write to store #%s (%s)"
msgstr "MultiBackend: _put: escribir en almacén #%s (%s)"

#: ../duplicity/backends/multibackend.py:272
#, python-format
msgid "MultiBackend: failed to write to store #%s (%s), try #%s, Exception: %s"
msgstr "MultiBackend: falló al escribir en almacén #%s (%s), intenta #%s, Excepción: %s"

#: ../duplicity/backends/multibackend.py:286
#, python-format
msgid "MultiBackend: failed to write %s. Aborting process."
msgstr "MultiBackend: falló al escribir %s. Abortando el proceso."

#: ../duplicity/backends/multibackend.py:294
#, python-format
msgid "MultiBackend: failed to write %s. Tried all backing stores and none succeeded"
msgstr "MultiBackend: falló al escribir %s. Se probaron todos los almacenes de copias y ninguno funcionó"

#: ../duplicity/backends/multibackend.py:315
#, python-format
msgid "MultiBackend: failed to get %s to %s from %s"
msgstr "MultiBackend: falló al obtener %s a %s de %s"

#: ../duplicity/backends/multibackend.py:320
#, python-format
msgid "MultiBackend: failed to get %s. Tried all backing stores and none succeeded"
msgstr "MultiBackend: falló al obtener %s. Se probaron todos los almacenes de copias y ninguno funcionó"

#: ../duplicity/backends/multibackend.py:330
#, python-format
msgid "MultiBackend: %s: %d files"
msgstr ""

#: ../duplicity/backends/multibackend.py:334
msgid "Exception during list of {s.backend.parsed_url.strip_auth()}: "
msgstr ""

#: ../duplicity/backends/multibackend.py:342
#, python-format
msgid "MultiBackend: combined list: %s"
msgstr "MultiBackend: lista combinada: %s"

#: ../duplicity/backends/multibackend.py:371
#: ../duplicity/backends/multibackend.py:398
#, python-format
msgid "MultiBackend: failed to delete %s. Tried all backing stores and none succeeded"
msgstr "MultiBackend: falló al eliminar %s. Se probaron todos los almacenes de copias y ninguno funcionó"

#: ../duplicity/backends/giobackend.py:108
#, python-format
msgid "Connection failed, please check your password: %s"
msgstr "Falló la conexión, compruebe su contraseña: %s"

#: ../duplicity/backends/onedrivebackend.py:90
#, python-format
msgid "Attempt of initialize_oauth2_session Nr. %s failed. %s: %s"
msgstr ""

#: ../duplicity/backends/webdavbackend.py:67
msgid "Missing socket or ssl python modules."
msgstr "Faltan los módulos de Python «socket» o «ssl»."

#: ../duplicity/backends/webdavbackend.py:87
#, python-format
msgid "Cacert database file '%s' is not readable."
msgstr "Archivo de base de datos Cacert «%s» ilegible."

#: ../duplicity/backends/webdavbackend.py:149
#, python-format
msgid "Using WebDAV host %s port %s"
msgstr "Usando servidor WebDAV %s puerto %s"

#: ../duplicity/backends/webdavbackend.py:150
#, python-format
msgid "Using WebDAV directory %s"
msgstr "Usando directorio de WebDAV %s"

#: ../duplicity/backends/webdavbackend.py:180
#, python-format
msgid "WebDAV create connection on '%s'"
msgstr "Conexión para creación de WebDAV en «%s»"

#: ../duplicity/backends/webdavbackend.py:191
#, python-format
msgid "WebDAV Unknown URI scheme: %s"
msgstr "Esquema de URI WebDAV desconocido: %s"

#: ../duplicity/backends/webdavbackend.py:210
#, python-format
msgid "WebDAV %s %s request with headers: %s "
msgstr "WebDAV %s %s petición con encabezados: %s "

#: ../duplicity/backends/webdavbackend.py:211
#: ../duplicity/backends/webdavbackend.py:234
#, python-format
msgid "WebDAV data length: %s "
msgstr "Longitud de datos de WebDAV: %s "

#: ../duplicity/backends/webdavbackend.py:214
#, python-format
msgid "WebDAV response status %s with reason '%s'."
msgstr "Estado de respuesta WebDAV %s con razón «%s»."

#: ../duplicity/backends/webdavbackend.py:220
#, python-format
msgid "WebDAV redirect to: %s "
msgstr "WebDAV redigir a: %s "

#: ../duplicity/backends/webdavbackend.py:222
msgid "WebDAV redirected 10 times. Giving up."
msgstr "WebDAV redirigido 10 veces. Abandonando."

#: ../duplicity/backends/webdavbackend.py:227
msgid "WebDAV missing location header in redirect response."
msgstr "A WebDAV le falta la cabecera de ubicación en la respuesta de redirección."

#: ../duplicity/backends/webdavbackend.py:232
msgid "WebDAV retry request with authentification headers."
msgstr "Petición de reintento de WebDAV con encabezados de autentificación."

#: ../duplicity/backends/webdavbackend.py:233
#, python-format
msgid "WebDAV %s %s request2 with headers: %s "
msgstr "WebDAV %s %s solicitud2 con encabezados: %s "

#: ../duplicity/backends/webdavbackend.py:237
#, python-format
msgid "WebDAV response2 status %s with reason '%s'."
msgstr "WebDAV respuesta2 estado %s con motivo «%s»."

#: ../duplicity/backends/webdavbackend.py:256
msgid "python-kerberos needed to use kerberos                           authorization, falling back to basic auth."
msgstr "python-kerberos necesitó usar la autorización kerberos, volviendo a la autorización básica."

#: ../duplicity/backends/webdavbackend.py:264
#, python-format
msgid "Kerberos authorization failed: %s.                          Falling back to basic auth."
msgstr "Falló autorización Kerberos: %s. Volviendo a autorización básica."

#: ../duplicity/backends/webdavbackend.py:365
#, python-format
msgid "Creating missing directory %s"
msgstr "Creando directorio que falta %s"

#: ../duplicity/backends/webdavbackend.py:369
#, python-format
msgid "WebDAV MKCOL %s failed: %s %s"
msgstr "WebDAV MKCOL %s falló: %s %s"

#: ../duplicity/backends/webdavbackend.py:381
#, python-format
msgid "WebDAV path decoding and translation: %s -> %s"
msgstr "Descodificación y traducción de rutas de WebDAV: %s → %s"

#: ../duplicity/backends/webdavbackend.py:421
#, python-format
msgid "WebDAV GET Bad status code %s reason %s."
msgstr "WebDAV GET Mal código de estado %s motivo %s."

#: ../duplicity/backends/webdavbackend.py:442
#, python-format
msgid "WebDAV PUT Bad status code %s reason %s."
msgstr "WebDAV PUT Mal código de estado %s motivo %s."

#: ../duplicity/backends/webdavbackend.py:461
#, python-format
msgid "WebDAV DEL Bad status code %s reason %s."
msgstr "WebDAV DEL Mal código de estado %s motivo %s."

#. Used in usage help to represent a Unix-style path name. Example:
#. --archive-dir <path>
#: ../duplicity/cli_data.py:102 ../duplicity/cli_data.py:162
#: ../duplicity/cli_data.py:196 ../duplicity/cli_data.py:243
#: ../duplicity/cli_data.py:346 ../duplicity/cli_data.py:364
#: ../duplicity/cli_data.py:524 ../duplicity/cli_data.py:706
#: ../duplicity/cli_data.py:932
msgid "path"
msgstr "ruta"

#: ../duplicity/cli_data.py:115
msgid "Hot|Cool|Archive"
msgstr ""

#. Used in usage help to represent a desired number of
#. something. Example:
#. --num-retries <number>
#: ../duplicity/cli_data.py:120 ../duplicity/cli_data.py:126
#: ../duplicity/cli_data.py:134 ../duplicity/cli_data.py:168
#: ../duplicity/cli_data.py:432 ../duplicity/cli_data.py:448
#: ../duplicity/cli_data.py:495 ../duplicity/cli_data.py:512
#: ../duplicity/cli_data.py:518 ../duplicity/cli_data.py:536
#: ../duplicity/cli_data.py:602 ../duplicity/cli_data.py:610
#: ../duplicity/cli_data.py:662 ../duplicity/cli_data.py:743
#: ../duplicity/cli_data.py:919
msgid "number"
msgstr "número"

#. Used in usage help. Example:
#. --timeout <seconds>
#: ../duplicity/cli_data.py:146 ../duplicity/cli_data.py:713
#: ../duplicity/cli_data.py:945
msgid "seconds"
msgstr "segundos"

#. Used in usage help to represent an ID for a GnuPG key. Example:
#. --encrypt-key <gpg_key_id>
#: ../duplicity/cli_data.py:184 ../duplicity/cli_data.py:190
#: ../duplicity/cli_data.py:358 ../duplicity/cli_data.py:669
#: ../duplicity/cli_data.py:911
msgid "gpg-key-id"
msgstr ""

#. Used in usage help to represent a "glob" style pattern for
#. matching one or more files, as described in the documentation.
#. Example:
#. --exclude <shell_pattern>
#: ../duplicity/cli_data.py:201 ../duplicity/cli_data.py:386
#: ../duplicity/cli_data.py:950
msgid "shell_pattern"
msgstr ""

#. Used in usage help to represent the name of a file. Example:
#. --log-file <filename>
#: ../duplicity/cli_data.py:213 ../duplicity/cli_data.py:219
#: ../duplicity/cli_data.py:279 ../duplicity/cli_data.py:392
#: ../duplicity/cli_data.py:908
msgid "filename"
msgstr "nombre de archivo"

#. Used in usage help to represent a time spec for a previous
#. point in time, as described in the documentation. Example:
#. duplicity remove-older-than time [options] target_url
#: ../duplicity/cli_data.py:225 ../duplicity/cli_data.py:549
#: ../duplicity/cli_data.py:976
msgid "time"
msgstr "hora"

#: ../duplicity/cli_data.py:237 ../duplicity/cli_data.py:398
msgid "regex"
msgstr ""

#: ../duplicity/cli_data.py:340
msgid "interval"
msgstr ""

#. Used in usage help. (Should be consistent with the "Options:"
#. header.) Example:
#. duplicity [full|incremental] [options] source_path target_url
#: ../duplicity/cli_data.py:352 ../duplicity/cli_data.py:506
#: ../duplicity/cli_data.py:555 ../duplicity/cli_data.py:685
#: ../duplicity/cli_data.py:923 ../duplicity/argparse311.py:1671
msgid "options"
msgstr "opciones"

#: ../duplicity/cli_data.py:381
msgid "imap_mailbox"
msgstr ""

#: ../duplicity/cli_data.py:406
msgid "If set, an extra file with statistics in json format will be stored with each backup. It includes the statistics printed out on stdout by default. With 'collection-status' it returs these stats."
msgstr ""

#: ../duplicity/cli_data.py:414
msgid "file_descriptor"
msgstr ""

#: ../duplicity/cli_data.py:421
msgid "log_filename"
msgstr ""

#: ../duplicity/cli_data.py:454
msgid "backup name"
msgstr "nombre de respaldo"

#: ../duplicity/cli_data.py:561
msgid "s3_endpoint_url"
msgstr ""

#: ../duplicity/cli_data.py:629
msgid "s3_kms_key_id"
msgstr ""

#: ../duplicity/cli_data.py:635
msgid "s3_kms_grant"
msgstr ""

#: ../duplicity/cli_data.py:641
msgid "s3_region_name"
msgstr ""

#: ../duplicity/cli_data.py:647
msgid "policy"
msgstr ""

#. noun
#: ../duplicity/cli_data.py:652 ../duplicity/cli_data.py:657
#: ../duplicity/cli_data.py:897
msgid "command"
msgstr "orden"

#: ../duplicity/cli_data.py:692
msgid "pem formatted bundle of certificate authorities"
msgstr "paquete formateado pem de entidades de certificación"

#: ../duplicity/cli_data.py:697
msgid "path to a folder with certificate authority files"
msgstr "ruta a una carpeta con archivos de autoridad de certificados"

#. abbreviation for "character" (noun)
#: ../duplicity/cli_data.py:719 ../duplicity/cli_data.py:895
msgid "char"
msgstr "carácter"

#: ../duplicity/cli_data.py:732
msgid "verb"
msgstr ""

#: ../duplicity/cli_data.py:750
msgid "extra headers for Webdav, like 'Cookie,name=value'"
msgstr ""

#. Used in usage help to represent a Unix-style path name. Example:
#. rsync://user[:password]@other_host[:port]//absolute_path
#: ../duplicity/cli_data.py:886
msgid "absolute_path"
msgstr "ruta_absoluta"

#. Used in usage help. Example:
#. tahoe://alias/some_dir
#: ../duplicity/cli_data.py:889
msgid "alias"
msgstr ""

#. Used in help to represent a "bucket name" for Amazon Web
#. Services' Simple Storage Service (S3). Example:
#. s3://other.host/bucket_name[/prefix]
#: ../duplicity/cli_data.py:893
msgid "bucket_name"
msgstr "nombre_cubo"

#. Used in usage help to represent the name of a container in
#. Amazon Web Services' Cloudfront. Example:
#. cf+http://container_name
#: ../duplicity/cli_data.py:901
msgid "container_name"
msgstr "nombre_contenedor"

#. noun
#: ../duplicity/cli_data.py:903
msgid "count"
msgstr "recuento"

#. Used in usage help to represent the name of a file directory
#: ../duplicity/cli_data.py:905
msgid "directory"
msgstr "directorio"

#. Used in usage help, e.g. to represent the name of a code
#. module. Example:
#. rsync://user[:password]@other.host[:port]::/module/some_dir
#: ../duplicity/cli_data.py:915
msgid "module"
msgstr "módulo"

#. Used in usage help to represent an internet hostname. Example:
#. ftp://user[:password]@other.host[:port]/some_dir
#: ../duplicity/cli_data.py:926
msgid "other.host"
msgstr "otro.host"

#. Used in usage help. Example:
#. ftp://user[:password]@other.host[:port]/some_dir
#: ../duplicity/cli_data.py:929
msgid "password"
msgstr "contraseña"

#. Used in usage help to represent a TCP port number. Example:
#. ftp://user[:password]@other.host[:port]/some_dir
#: ../duplicity/cli_data.py:935
msgid "port"
msgstr "puerto"

#. Used in usage help. This represents a string to be used as a
#. prefix to names for backup files created by Duplicity. Example:
#. s3://other.host/bucket_name[/prefix]
#: ../duplicity/cli_data.py:939
msgid "prefix"
msgstr "prefijo"

#. Used in usage help to represent a Unix-style path name. Example:
#. rsync://user[:password]@other.host[:port]/relative_path
#: ../duplicity/cli_data.py:942
msgid "relative_path"
msgstr "ruta_relativa"

#. Used in usage help to represent the name of a single file
#. directory or a Unix-style path to a directory. Example:
#. file:///some_dir
#: ../duplicity/cli_data.py:954
msgid "some_dir"
msgstr "algun_dir"

#. Used in usage help to represent the name of a single file
#. directory or a Unix-style path to a directory where files will be
#. coming FROM. Example:
#. duplicity [full|incremental] [options] source_path target_url
#: ../duplicity/cli_data.py:959
msgid "source_path"
msgstr ""

#. Used in usage help to represent a URL files will be coming
#. FROM. Example:
#. duplicity [restore] [options] source_url target_dir
#: ../duplicity/cli_data.py:963
msgid "source_url"
msgstr "url_origen"

#. Used in usage help to represent the name of a single file
#. directory or a Unix-style path to a directory. where files will be
#. going TO. Example:
#. duplicity [restore] [options] source_url target_dir
#: ../duplicity/cli_data.py:968
msgid "target_dir"
msgstr "dir_objetivo"

#. Used in usage help to represent a URL files will be going TO.
#. Example:
#. duplicity [full|incremental] [options] source_path target_url
#: ../duplicity/cli_data.py:972
msgid "target_url"
msgstr "url_objetivo"

#. Used in usage help to represent a user name (i.e. login).
#. Example:
#. ftp://user[:password]@other.host[:port]/some_dir
#: ../duplicity/cli_data.py:980
msgid "user"
msgstr "usuario"

#. account id for b2. Example: b2://account_id@bucket/
#: ../duplicity/cli_data.py:982
msgid "account_id"
msgstr "id_cuenta"

#. application_key for b2.
#. Example: b2://account_id:application_key@bucket/
#: ../duplicity/cli_data.py:985
msgid "application_key"
msgstr "clave_aplicación"

#. remote name for rclone.
#. Example: rclone://remote:/some_dir
#: ../duplicity/cli_data.py:988 ../duplicity/dup_collections.py:565
msgid "remote"
msgstr "remoto"

#: ../duplicity/cli_data.py:992
msgid "Backends and their URL formats:"
msgstr "Motores y sus formatos de URL:"

#: ../duplicity/diffdir.py:102 ../duplicity/diffdir.py:401
#, python-format
msgid "Error %s getting delta for %s"
msgstr "Error %s consiguiendo el delta para %s"

#: ../duplicity/diffdir.py:116
#, python-format
msgid "Getting delta of %s and %s"
msgstr "Consiguiendo el delta de %s y %s"

#: ../duplicity/diffdir.py:160
#, python-format
msgid "A %s"
msgstr ""

#: ../duplicity/diffdir.py:168
#, python-format
msgid "M %s"
msgstr ""

#: ../duplicity/diffdir.py:191
#, python-format
msgid "Comparing %s and %s"
msgstr "Comparando %s y %s"

#: ../duplicity/diffdir.py:204
#, python-format
msgid "D %s"
msgstr ""

#: ../duplicity/librsync.py:194
msgid "basis_file must be a (true) file or an object whose file attribute is the underlying true file object"
msgstr "basis_file debe ser un archivo (verdadero) o un objeto cuyos atributos de archivo son el objeto del archivo verdadero subyacente"

#: ../duplicity/dup_time.py:54
#, python-format
msgid "Bad interval string \"%s\"\n\n"
"Intervals are specified like 2Y (2 years) or 2h30m (2.5 hours).  The\n"
"allowed special characters are s, m, h, D, W, M, and Y.  See the man\n"
"page for more information."
msgstr "Cadena de intervalo errónea «%s»\n\n"
"Los intervalos son del tipo 2Y (2 años) o 2h30m (2.5 horas). \n"
"Los caracteres especiales permitidos son s, m, h, D, W, M e Y.\n"
"Ver el manual para más información."

#: ../duplicity/dup_time.py:63
#, python-format
msgid "Bad time string \"%s\"\n\n"
"The acceptible time strings are intervals (like \"3D64s\"), w3-datetime\n"
"strings, like \"2002-04-26T04:22:01-07:00\" (strings like\n"
"\"2002-04-26T04:22:01\" are also acceptable - duplicity will use the\n"
"current time zone), or ordinary dates like 2/4/1997 or 2001-04-23\n"
"(various combinations are acceptable, but the month always precedes\n"
"the day)."
msgstr "Cadena de fecha incorrecta «%s»\n\n"
"Las cadenas de fecha aceptable son intervalos (tipo «3D64s»), cadenas w3-datetime\n"
", tipo «2002-04-26T04:22:01-07:00» (cadenas tipo\n"
"«2002-04-26T04:22:01» son aceptables - duplicity usará la zona\n"
"horaria actual), o fecha normales tipo 2/4/1997 o 2001-04-23\n"
"(son aceptables distintas combinaciones, pero el mes debe preceder\n"
" al día siempre)."

#: ../duplicity/cli_main.py:155
msgid "No valid action found. Will imply 'backup' because a path source was given and target is a url location."
msgstr ""

#: ../duplicity/cli_main.py:163
msgid "No valid action found. Will imply 'restore' because url source was given and target is a local path."
msgstr ""

#: ../duplicity/cli_main.py:170
#, python-brace-format
msgid "Invalid '{remainder[0]}' action and cannot be implied from the "
msgstr ""

#: ../duplicity/cli_main.py:291
#, python-brace-format
msgid "GPG binary is {config.gpg_binary}, version {gpg_version}"
msgstr ""

#: ../duplicity/cli_main.py:327
#, python-brace-format
msgid "Using archive dir: {config.archive_dir_path.uc_name}"
msgstr ""

#: ../duplicity/cli_main.py:328
#, python-brace-format
msgid "Using backup name: {config.backup_name}"
msgstr ""

#: ../duplicity/dup_main.py:113
msgid "Reuse configured PASSPHRASE as SIGN_PASSPHRASE"
msgstr "Reusar configurar PASSPHRASE como SIGN_PASSPHRASE"

#: ../duplicity/dup_main.py:124
msgid "Reuse configured SIGN_PASSPHRASE as PASSPHRASE"
msgstr "Reusar configurar SIGN_PASSPHRASE como PASSPHRASE"

#: ../duplicity/dup_main.py:168
msgid "PASSPHRASE variable not set, asking user."
msgstr "Variable PASSPHRASE no establecida, preguntar al usuario."

#: ../duplicity/dup_main.py:193
msgid "Retype passphrase for signing key to confirm: "
msgstr "Vuelva a teclear la frase de paso de la clave firmada para confirmar: "

#: ../duplicity/dup_main.py:195
msgid "Retype passphrase for decryption to confirm: "
msgstr ""

#: ../duplicity/dup_main.py:199
msgid "First and second passphrases do not match!  Please try again."
msgstr "¡La primera y segunda contraseña no coinciden! Por favor inténtelo de nuevo."

#: ../duplicity/dup_main.py:210
msgid "Cannot use empty passphrase with symmetric encryption!  Please try again."
msgstr "¡No puede usar una contraseña en blanco con cifrado asimétrico! Por favor inténtelo de nuevo."

#: ../duplicity/dup_main.py:270
#, python-format
msgid "File %s complete in backup set.\n"
"Continuing restart on file %s."
msgstr "El archivo %s está competo en el conjunto de respaldo.\n"
"Continuar la restauración en el archivo %s."

#: ../duplicity/dup_main.py:280
#, python-format
msgid "File %s missing in backup set.\n"
"Continuing restart on file %s."
msgstr "El archivo %s  falta en el conjunto de respaldo.\n"
"Reinicio continuo en el archivo %s."

#: ../duplicity/dup_main.py:335
#, python-format
msgid "%s Remote filesize %d for %s does not match local size %d, retrying."
msgstr ""

#: ../duplicity/dup_main.py:342
#, python-format
msgid "File %s was corrupted during upload."
msgstr "El archivo %s se ha dañado en la carga."

#: ../duplicity/dup_main.py:382
msgid "Restarting backup, but current encryption settings do not match original settings"
msgstr "Reiniciando copia de respaldo, pero la configuración actual de cifrado no coincide con la configuración original"

#: ../duplicity/dup_main.py:404
msgid "Skipping encryption validation due to glacier/deep storage"
msgstr ""

#: ../duplicity/dup_main.py:408
#, python-format
msgid "Restarting after volume %s, file %s, block %s"
msgstr "Reiniciando tras volumen %s, archivo %s, bloque %s"

#: ../duplicity/dup_main.py:471
msgid "Skipped volume upload, as effectivly nothing has changed"
msgstr ""

#: ../duplicity/dup_main.py:485
#, python-format
msgid "Processed volume %d"
msgstr "Se procesó el volumen %d"

#: ../duplicity/dup_main.py:653
msgid "Fatal Error: Unable to start incremental backup.  Old signatures not found and incremental specified"
msgstr "Error Fatal: No se puede iniciar respaldo incremental. Firmas de edad y que no se encuentran especificados incremental"

#: ../duplicity/dup_main.py:659
msgid "No signatures found, switching to full backup."
msgstr "Firmas no encontradas, cambiando a un backup completo."

#: ../duplicity/dup_main.py:673
msgid "Backup Statistics"
msgstr "Estadísticas de respaldo"

#: ../duplicity/dup_main.py:813
#, python-format
msgid "%s not found in archive - no files restored."
msgstr "No se encontró %s en el archivador; no se restauró ningún archivo."

#: ../duplicity/dup_main.py:817
msgid "No files found in archive - nothing restored."
msgstr "No se encontraron archivos en el archivador - nada que restaurar."

#: ../duplicity/dup_main.py:853
#, python-format
msgid "Processed volume %d of %d"
msgstr "Volumen procesado %d de %d"

#: ../duplicity/dup_main.py:896
#, python-format
msgid "Invalid data - %s hash mismatch for file:"
msgstr "datos no válidos - %s hash no coincide con archivo:"

#: ../duplicity/dup_main.py:898
#, python-format
msgid "Calculated hash: %s"
msgstr "hash calculado: %s"

#: ../duplicity/dup_main.py:899
#, python-format
msgid "Manifest hash: %s"
msgstr "Manifestar hass: %s"

#: ../duplicity/dup_main.py:952
#, python-format
msgid "Volume was signed by key %s, not %s"
msgstr "El volumen fue firmado por %s clave, no %s"

#: ../duplicity/dup_main.py:984
#, python-format
msgid "Verify complete: %s, %s."
msgstr "Verificación completa: %s, %s."

#: ../duplicity/dup_main.py:985
#, python-format
msgid "%d file(s) compared"
msgstr ""

#: ../duplicity/dup_main.py:985
#, python-format
msgid "%d difference(s) found"
msgstr ""

#: ../duplicity/dup_main.py:1004
msgid "No extraneous files found, nothing deleted in cleanup."
msgstr "Ningún archivo raro encontrado, nada borrado al acabar."

#: ../duplicity/dup_main.py:1019
msgid "Found the following file(s) to delete:"
msgstr ""

#: ../duplicity/dup_main.py:1023
msgid "Run duplicity again with the --force option to actually delete."
msgstr "Ejecutar duplicity de nuevo con la opción --foirce para eliminar realmente."

#: ../duplicity/dup_main.py:1069
msgid "There are backup set(s) at time(s):"
msgstr "Hay conjuntos de respaldo con hora:"

#: ../duplicity/dup_main.py:1071
msgid "Which can't be deleted because newer sets depend on them."
msgstr "Que no se puede eliminar porque los nuevos conjuntos dependen de ellos."

#: ../duplicity/dup_main.py:1078
msgid "Current active backup chain is older than specified time.  However, it will not be deleted.  To remove all your backups, manually purge the repository."
msgstr "La cadena del respaldo activo actual es anterior a la hora especificada, por lo que no se eliminará. Para eliminar todos sus respaldos, purgue manualmente el repositiorio."

#: ../duplicity/dup_main.py:1096
msgid "No old backup sets found, nothing deleted."
msgstr "No se encontraron respaldos. nada que eliminar."

#: ../duplicity/dup_main.py:1099
msgid "Deleting backup chain(s) at time:"
msgstr ""

#: ../duplicity/dup_main.py:1108
#, python-format
msgid "Deleting any incremental signature chain rooted at %s"
msgstr "Eliminando cualquier cadena de firmado incremental con origen en %s"

#: ../duplicity/dup_main.py:1110
#, python-format
msgid "Deleting any incremental backup chain rooted at %s"
msgstr "Eliminando cualquier copia de seguridad incremental con origen en %s"

#: ../duplicity/dup_main.py:1113
#, python-format
msgid "Deleting complete signature chain %s"
msgstr "Borrando cadenas de firmas completas %s"

#: ../duplicity/dup_main.py:1115
#, python-format
msgid "Deleting complete backup chain %s"
msgstr "Borrando cadena de copias de seguridad completas %s"

#: ../duplicity/dup_main.py:1122
msgid "Found old backup chain(s) at the following time:"
msgstr ""

#: ../duplicity/dup_main.py:1126
msgid "Rerun command with --force option to actually delete."
msgstr "Volviendo a ejecutar orden con la opción --force para eliminar realmente."

#: ../duplicity/dup_main.py:1229
#, python-format
msgid "Deleting local %s (not authoritative at backend)."
msgstr "Eliminación local %s (No es una autoridad en el procesamiento)"

#: ../duplicity/dup_main.py:1233
#, python-format
msgid "Unable to delete %s: %s"
msgstr "No se puede eliminar %s: %s"

#: ../duplicity/dup_main.py:1267 ../duplicity/dup_temp.py:296
#, python-format
msgid "Failed to read %s: %s"
msgstr "No se pudo leer %s: %s"

#: ../duplicity/dup_main.py:1279
#, python-format
msgid "Copying %s to local cache."
msgstr "Copiando %s a la caché local."

#: ../duplicity/dup_main.py:1327
msgid "Local and Remote metadata are synchronized, no sync needed."
msgstr "Los metadatos en local y remoto están sincronizados, no es necesario sincronizar."

#: ../duplicity/dup_main.py:1332
msgid "Synchronizing remote metadata to local cache..."
msgstr "Sincronizando metadatos remotos con la caché local..."

#: ../duplicity/dup_main.py:1346
msgid "Sync would copy the following from remote to local:"
msgstr "Sync copiaría lo siguiente de remoto a local:"

#: ../duplicity/dup_main.py:1352
msgid "Sync would remove the following spurious local files:"
msgstr "Sync eliminaría los siguientes archivos locales:"

#: ../duplicity/dup_main.py:1398
msgid "Unable to get free space on temp."
msgstr "Imposible conseguir espacio libre en temp."

#: ../duplicity/dup_main.py:1405
#, python-format
msgid "Temp space has %d available, backup needs approx %d."
msgstr "Espacio temporal tiene %d disponibles, copias de seguridad necesitan aproximadamente %d."

#: ../duplicity/dup_main.py:1409
#, python-format
msgid "Temp has %d available, backup will use approx %d."
msgstr "Temp tiene %d disponible, el respaldo usará aproximadamente %d."

#: ../duplicity/dup_main.py:1416
msgid "Unable to get max open files."
msgstr "No se puede obtener archivos de máxima apertura."

#: ../duplicity/dup_main.py:1421
#, python-format
msgid "Max open files of %s is too low, should be >= 1024.\n"
"Use 'ulimit -n 1024' or higher to correct.\n"
msgstr "El máximo de archivos abiertos %s es demasiado pequeño, debería ser >= 1.024.\n"
"Utilice «ulimit -n 1024» o más alto para corregirlo.\n"

#: ../duplicity/dup_main.py:1477
msgid "RESTART: The first volume failed to upload before termination.\n"
"         Restart is impossible...starting backup from beginning."
msgstr "REINICIAR: El primer volumen no se han cargado antes de la terminación.\n"
"         Reiniciar es imposible... iniciando respaldo desde el principio."

#: ../duplicity/dup_main.py:1487
#, python-format
msgid "RESTART: Volumes %d to %d failed to upload before termination.\n"
"         Restarting backup at volume %d."
msgstr "REINICIAR: Volúmenes %d a %d fallaron al cargar antes de terminar.\n"
"         Reiniciar copia de respaldo en el volumen %d."

#: ../duplicity/dup_main.py:1498
#, python-format
msgid "RESTART: Impossible backup state: manifest has %d vols, remote has %d vols.\n"
"         Restart is impossible ... duplicity will clean off the last partial\n"
"         backup then restart the backup from the beginning."
msgstr "REINICIAR: Estado de copia de respaldo no posible: manifesto tiene %d vols, remoto tiene %d vols.\n"
"         Reiniciar no es posible .. duplicity limpiará la última copia de respaldo parcial\n"
"         y reiniciará la copia desde el principio."

#: ../duplicity/dup_main.py:1523
msgid "PYTHONOPTIMIZE in the environment causes duplicity to fail to\n"
"recognize its own backups.  Please remove PYTHONOPTIMIZE from\n"
"the environment and rerun the backup.\n\n"
"See https://bugs.launchpad.net/duplicity/+bug/931175\n"
msgstr ""

#: ../duplicity/dup_main.py:1549
#, python-format
msgid "Acquiring lockfile %s"
msgstr "Adquiriendo candado %s"

#: ../duplicity/dup_main.py:1609
#, python-brace-format
msgid "Last {action} backup left a partial set, restarting."
msgstr ""

#: ../duplicity/dup_main.py:1613
#, python-brace-format
msgid "Cleaning up previous partial {action} backup set, restarting."
msgstr ""

#: ../duplicity/dup_main.py:1627
msgid "Last full backup date: none"
msgstr "Fecha del último respaldo completo: ninguna"

#: ../duplicity/dup_main.py:1634
msgid "Last full backup is too old, forcing full backup"
msgstr "El último respaldo completo es demasiado viejo, lo que obligó a una copia de seguridad completa"

#: ../duplicity/dup_main.py:1690
msgid "When using symmetric encryption, the signing passphrase must equal the encryption passphrase."
msgstr "Al usar el cifrado simétrico, la contraseña de firmado debe coincidir con la de cifrado."

#: ../duplicity/asyncscheduler.py:259
#, python-format
msgid "task execution done (success: %s)"
msgstr "ejecución de la tarea realizada (éxito: %s)"

#: ../duplicity/gpginterface.py:694
#, python-brace-format
msgid "GPG process {process.pid} terminated before wait()"
msgstr ""

#: ../duplicity/robust.py:84
#, python-format
msgid "Error listing directory %s"
msgstr "Error al escuchar el directorio %s"

#: ../duplicity/dup_collections.py:200 ../duplicity/dup_collections.py:209
#, python-format
msgid "BackupSet.delete: missing %s"
msgstr "BackupSet.delete: falta %s"

#: ../duplicity/dup_collections.py:235
msgid "Fatal Error: No manifests found for most recent backup"
msgstr "Error fatal: no se encontraron manifiestos para el respaldo más reciente"

#: ../duplicity/dup_collections.py:248
msgid "Fatal Error: Remote manifest does not match local one.  Either the remote backup set or the local archive directory has been corrupted."
msgstr "Error fatal: el manifiesto remoto no coincide con el local. Ni la configuración de copia de seguridad remota o el directorio del archivo local está dañado."

#: ../duplicity/dup_collections.py:256
#, python-format
msgid "Error processing remote manifest (%s): %s"
msgstr "Error al procesar el manifiesto remoto (%s): %s"

#: ../duplicity/dup_collections.py:265
msgid "Fatal Error: Neither remote nor local manifest is readable."
msgstr "Error fatal: ni el manifiesto remoto ni el local son legibles"

#: ../duplicity/dup_collections.py:276
#, python-format
msgid "Processing local manifest %s (%s)"
msgstr "Procesando manifiesto local %s (%s)"

#: ../duplicity/dup_collections.py:291
msgid "Error processing remote file ({os.fsdecode(remote_file)}): {util.uexc(message)}"
msgstr ""

#: ../duplicity/dup_collections.py:293
msgid "Processing remote file {os.fsdecode(remote_file)} ({len(remote_file_buffer)})"
msgstr ""

#: ../duplicity/dup_collections.py:311
msgid "No Jsonstat file found, return enmty."
msgstr ""

#: ../duplicity/dup_collections.py:404
msgid "Preferring Backupset over previous one!"
msgstr "Preferir la configuración de copia de seguridad previa"

#: ../duplicity/dup_collections.py:408
#, python-format
msgid "Ignoring incremental Backupset (start_time: %s; needed: %s)"
msgstr "Ignorar la configuración de copia de seguridad incremental (start_time: %s; necesaria: %s)"

#: ../duplicity/dup_collections.py:417
#, python-format
msgid "Added incremental Backupset (start_time: %s / end_time: %s)"
msgstr "Añadida configuración de copia de seguridad incremental (start_time: %s / end_time: %s)"

#: ../duplicity/dup_collections.py:490
msgid "Chain start time: "
msgstr "Hora de inicio de la cadena: "

#: ../duplicity/dup_collections.py:491
msgid "Chain end time: "
msgstr "Hora de terminación de la cadena: "

#: ../duplicity/dup_collections.py:492
#, python-format
msgid "Number of contained backup sets: %d"
msgstr "Número de conjuntos de respaldo contenidos: %d"

#: ../duplicity/dup_collections.py:493
#, python-format
msgid "Total number of contained volumes: %d"
msgstr "Número total de volúmenes contenidos: %d"

#: ../duplicity/dup_collections.py:494 ../duplicity/dup_collections.py:1308
msgid "Type of backup set:"
msgstr "Tipo de conjunto de respaldo"

#: ../duplicity/dup_collections.py:494 ../duplicity/dup_collections.py:1308
msgid "Time:"
msgstr "Hora:"

#: ../duplicity/dup_collections.py:494
msgid "Num volumes:"
msgstr "Número de volúmenes:"

#: ../duplicity/dup_collections.py:499 ../duplicity/dup_collections.py:1315
msgid "Full"
msgstr "Completo"

#: ../duplicity/dup_collections.py:502 ../duplicity/dup_collections.py:1317
msgid "Incremental"
msgstr ""

#: ../duplicity/dup_collections.py:563
msgid "local"
msgstr ""

#: ../duplicity/dup_collections.py:726
msgid "Collection Status"
msgstr "Estado de la colección"

#: ../duplicity/dup_collections.py:728
#, python-format
msgid "Connecting with backend: %s"
msgstr "Conectar con el motor: %s"

#: ../duplicity/dup_collections.py:729
#, python-format
msgid "Archive dir: %s"
msgstr "Directorio de archivador: %s"

#: ../duplicity/dup_collections.py:732
#, python-format
msgid "Found %d secondary backup chain(s)."
msgstr ""

#: ../duplicity/dup_collections.py:734
#, python-format
msgid "Secondary chain %d of %d:"
msgstr "Cadena secundaria %d de %d:"

#: ../duplicity/dup_collections.py:739
msgid "Found primary backup chain with matching signature chain:"
msgstr "Se encontró cadena de copia de seguridad primaria con cadena de firma coincidente:"

#: ../duplicity/dup_collections.py:742
msgid "No backup chains with active signatures found"
msgstr "No encontró cadenas con firmas activas"

#: ../duplicity/dup_collections.py:745
#, python-format
msgid "Also found %d backup set(s) not part of any chain,"
msgstr ""

#: ../duplicity/dup_collections.py:746
#, python-format
msgid "and %d incomplete backup set(s)."
msgstr ""

#. "cleanup" is a hard-coded command, so do not translate it
#: ../duplicity/dup_collections.py:748
msgid "These may be deleted by running duplicity with the \"cleanup\" command."
msgstr "Esto se puede eliminar ejecutando duplicity con la orden «cleanup»"

#: ../duplicity/dup_collections.py:750
msgid "No orphaned or incomplete backup sets found."
msgstr "No se han encontrado respaldos huérfanos o incompletos."

#: ../duplicity/dup_collections.py:766
#, python-format
msgid "%d file(s) exists on backend"
msgstr ""

#: ../duplicity/dup_collections.py:772
#, python-format
msgid "%d file exists in cache"
msgid_plural "%d files exist in cache"
msgstr[0] ""
msgstr[1] ""

#: ../duplicity/dup_collections.py:831
msgid "Warning, discarding last backup set, because of missing signature file."
msgstr "Aviso, descartando el último conjunto de respaldo, debido a la falta archivo de firma."

#: ../duplicity/dup_collections.py:854
msgid "Warning, found the following local orphaned signature file(s):"
msgstr ""

#: ../duplicity/dup_collections.py:862
msgid "Warning, found the following remote orphaned signature file(s):"
msgstr ""

#: ../duplicity/dup_collections.py:870
msgid "Warning, found signatures but no corresponding backup files"
msgstr "Aviso, se encontraron firmas pero no coinciden con los archivos de copia de seguridad"

#: ../duplicity/dup_collections.py:876
msgid "Warning, found incomplete backup sets, probably left from aborted session"
msgstr "Aviso, encontró conjuntos de copia de seguridad incompletos, probablemente de la sesión abortada"

#: ../duplicity/dup_collections.py:882
msgid "Warning, found the following orphaned backup file(s):"
msgstr ""

#: ../duplicity/dup_collections.py:897
#, python-format
msgid "Extracting backup chains from list of files: %s"
msgstr "Extrayendo cadenas de respaldo de la lista de archivos: %s"

#: ../duplicity/dup_collections.py:908
#, python-format
msgid "File %s is part of known set"
msgstr "El archivo %s es parte del conjunto conocido"

#: ../duplicity/dup_collections.py:911
#, python-format
msgid "File %s is not part of a known set; creating new set"
msgstr "El archivo %s no es parte de un conjunto conocido; creando un conjunto nuevo"

#: ../duplicity/dup_collections.py:916
#, python-format
msgid "Ignoring file (rejected by backup set) '%s'"
msgstr "Ignorando archivo (rechazado por el conjunto) «%s»"

#: ../duplicity/dup_collections.py:932
#, python-format
msgid "Found backup chain %s"
msgstr "Se encontró una cadena de respaldo %s"

#: ../duplicity/dup_collections.py:937
#, python-format
msgid "Added set %s to pre-existing chain %s"
msgstr "conjunto %s añadido a la cadena %s preexistente"

#: ../duplicity/dup_collections.py:940
#, python-format
msgid "Found orphaned set %s"
msgstr "Se encontró un conjunto huérfano %s"

#: ../duplicity/dup_collections.py:1088
#, python-format
msgid "No signature chain for the requested time. Using oldest available chain, starting at time %s."
msgstr "No hay cadena de firmas disponibles para la hora solicitada. Se está usando la cadena más antigua disponible, que comienza en %s."

#: ../duplicity/dup_collections.py:1306
#, python-format
msgid "File: %s"
msgstr "Archivo: %s"

#: ../duplicity/dup_collections.py:1307
#, python-format
msgid "Total number of backup: %d"
msgstr "Número total de copias de seguridad: %d"

#: ../duplicity/dup_collections.py:1308 ../duplicity/dup_collections.py:1344
msgid "Type of file change:"
msgstr "Tipo de cambio de archivo:"

#: ../duplicity/dup_collections.py:1342
#, python-format
msgid " Backup set time: %s"
msgstr ""

#: ../duplicity/dup_collections.py:1343
#, python-format
msgid "Total number of changes: %d"
msgstr ""

#: ../duplicity/dup_collections.py:1344
msgid "File:"
msgstr ""

#: ../duplicity/patchdir.py:72 ../duplicity/patchdir.py:79
#, python-format
msgid "Patching %s"
msgstr "Parcheando %s"

#: ../duplicity/patchdir.py:547
#, python-format
msgid "Error '%s' patching %s"
msgstr "Error «%s» parcheando %s"

#: ../duplicity/patchdir.py:624
#, python-format
msgid "Writing %s of type %s"
msgstr "Escribiendo %s del tipo %s"

#: ../duplicity/selection.py:115
#, python-format
msgid "Skipping socket %s"
msgstr "Omitiendo el zócalo %s"

#: ../duplicity/selection.py:121
#, python-format
msgid "Error initializing file %s"
msgstr "Error al inicializar el archivo %s"

#: ../duplicity/selection.py:127 ../duplicity/selection.py:167
#: ../duplicity/selection.py:615
#, python-format
msgid "Error accessing possibly locked file %s"
msgstr "Error al acceder a un archivo posiblemente bloqueado %s"

#: ../duplicity/selection.py:182
#, python-format
msgid "Warning: base %s doesn't exist, continuing"
msgstr "Aviso: %s base no existe, continuando"

#: ../duplicity/selection.py:184 ../duplicity/selection.py:205
#: ../duplicity/selection.py:208
#, python-format
msgid "Selecting %s"
msgstr "Seleccionando %s"

#: ../duplicity/selection.py:263
#, python-format
msgid "                The last file selection option is the filter option %s, which will have no\n"
"                effect as there are no subsequent file selection options. Exiting because\n"
"                this probably isn't what you meant."
msgstr ""

#: ../duplicity/selection.py:278
#, python-format
msgid "                Only these filter mode options were specified:\n"
"                    %s\n"
"                Case sensitive globbing is the default behaviour and so this has no effect.\n"
"                Exiting because this probably isn't what you meant."
msgstr ""

#: ../duplicity/selection.py:346
#, python-format
msgid "                Fatal Error: The file specification\n"
"                    %s\n"
"                cannot match any files in the base directory\n"
"                    %s\n"
"                Useful file specifications begin with the base directory or some\n"
"                pattern (such as '**') which matches the base directory."
msgstr ""

#: ../duplicity/selection.py:360
#, python-format
msgid "Fatal Error while processing expression\n"
"%s"
msgstr "Error fatal al procesar la expresión\n"
"%s"

#: ../duplicity/selection.py:378
#, python-format
msgid "Reading files to backup from list %s"
msgstr ""

#: ../duplicity/selection.py:403
#, python-format
msgid "                Files-from list contains the absolute path:\n"
"                    %s\n"
"                All paths specified in a files-from list must be given relative to the backup\n"
"                source path."
msgstr ""

#: ../duplicity/selection.py:418
msgid "                Files-from list specified which contains no files, the backup will be empty as\n"
"                a result. Exiting as this probably isn't what you meant,"
msgstr ""

#: ../duplicity/selection.py:435
#, python-format
msgid "                Last selection expression:\n"
"                    %s\n"
"                only specifies that files be included.  Because the default is to\n"
"                include all files, the expression is redundant.  Exiting because this\n"
"                probably isn't what you meant."
msgstr ""

#: ../duplicity/selection.py:497
#, python-format
msgid "Reading %s filelist %s"
msgstr ""

#: ../duplicity/selection.py:538
#, python-format
msgid "Error compiling regular expression %s"
msgstr "Error al compilar la expresión regular %s"

#: ../duplicity/lazy.py:349
#, python-format
msgid "Warning: oldindex %s >= newindex %s"
msgstr "Aviso: índice antiguo %s >= nuevo índice %s"

#: ../duplicity/lazy.py:424
#, python-format
msgid "Error '%s' processing %s"
msgstr "Error «%s» procesando %s"

#: ../duplicity/lazy.py:436
#, python-format
msgid "Skipping %s because of previous error"
msgstr "Omitiendo %s debido al error anterior"

#: ../duplicity/path.py:109
#, python-format
msgid "Warning: %s invalid devnums (0x%X), treating as (0, 0)."
msgstr "Aviso: %s devnums inválidos (0x%X), tratando como (0, 0)."

#: ../duplicity/path.py:239 ../duplicity/path.py:299
#, python-format
msgid "Warning: %s has negative mtime, treating as 0."
msgstr "Aviso: %s tiene mtime negativo, tratando como 0."

#: ../duplicity/path.py:372
#, python-format
msgid "New file %s"
msgstr "Archiv nuevo %s"

#: ../duplicity/path.py:375
#, python-format
msgid "File %s is missing"
msgstr "Falta el archivo %s"

#: ../duplicity/path.py:378
#, python-format
msgid "File %%s has type %s, expected %s"
msgstr "El archivo %%s tiene el tipo %s, se esperaba %s"

#: ../duplicity/path.py:383 ../duplicity/path.py:412
#, python-format
msgid "File %%s has permissions %s, expected %s"
msgstr "El archivo %%s tiene permisos %s, se esperaba %s"

#: ../duplicity/path.py:389
#, python-format
msgid "File %%s has mtime %s, expected %s"
msgstr "El archivo %%s tiene mtime %s, se esperaba %s"

#: ../duplicity/path.py:400
#, python-format
msgid "Data for file %s is different"
msgstr "Los datos para el archivo %s son diferentes"

#: ../duplicity/path.py:408
#, python-format
msgid "Symlink %%s points to %s, expected %s"
msgstr "El vínculo simbólico %%s apunta a %s, se esperaba %s"

#: ../duplicity/path.py:415
#, python-format
msgid "Device file %%s has numbers %s, expected %s"
msgstr "El archivo de dispositivo %%s tiene números %s, se esperaba %s"

#: ../duplicity/path.py:605
#, python-format
msgid "Making directory %s"
msgstr "Haciendo directorio %s"

#: ../duplicity/path.py:615
#, python-format
msgid "Deleting %s"
msgstr "Borrando %s"

#: ../duplicity/path.py:624
#, python-format
msgid "Touching %s"
msgstr "Tocando %s"

#: ../duplicity/path.py:632
#, python-format
msgid "Deleting tree %s"
msgstr "Eliminando árbol %s"

#: ../duplicity/cli_util.py:48
msgid "Enter 'duplicity --help' for help screen."
msgstr ""

#: ../duplicity/cli_util.py:127
msgid "Running in 'ignore errors' mode due to --ignore-errors.\n"
"Please reconsider if this was not intended"
msgstr ""

#: ../duplicity/cli_util.py:139
msgid "Use of the --asynchronous-upload option is experimental and not safe for production! There are reported cases of undetected data loss during upload. Be aware and periodically verify your backups to be safe."
msgstr ""

#: ../duplicity/cli_util.py:152
msgid "'{val}' is not an int: {str(e)}"
msgstr ""

#: ../duplicity/cli_util.py:166
#, python-brace-format
msgid "'{val} is not a single character."
msgstr ""

#: ../duplicity/cli_util.py:193
#, python-brace-format
msgid "Source should be pathname, not url.  Got '{val}' instead."
msgstr ""

#: ../duplicity/cli_util.py:195
#, python-brace-format
msgid "Argument source_path '{val}' does not exist."
msgstr ""

#: ../duplicity/cli_util.py:201
#, python-brace-format
msgid "Source should be url, not directory.  Got '{val}' instead."
msgstr ""

#: ../duplicity/cli_util.py:207
#, python-brace-format
msgid "Target should be directory, not url.  Got '{val}' instead."
msgstr ""

#: ../duplicity/cli_util.py:212
msgid "Unable to create target dir '{val}': {str(e)}"
msgstr ""

#: ../duplicity/cli_util.py:218
#, python-brace-format
msgid "Target should be url, not directory.  Got '{val}' instead."
msgstr ""

#: ../duplicity/cli_util.py:263
msgid "Verbosity must be one of: digit [0-9], character [ewnid],\n"
"or word ['error', 'warning', 'notice', 'info', 'debug'].\n"
"The default is 3 (Notice).  It is strongly recommended\n"
"that verbosity level is set at 2 (Warning) or higher."
msgstr ""

#: ../duplicity/cli_util.py:399
#, python-brace-format
msgid "Specified archive directory '{archive_dir_path.uc_name}' is not a directory"
msgstr ""

#: ../duplicity/cli_util.py:408
msgid "Encrypt key should be an 8, 16, or 40 character hex string, like 'AA0E73D2'.\n"
msgstr ""

#: ../duplicity/cli_util.py:428
msgid "Hidden dncrypt key should be an 8, 16, or 40 character hex string, like 'AA0E73D2'.\n"
msgstr ""

#: ../duplicity/cli_util.py:442
msgid "Sign key should be an 8, 16, or 40 character hex string, like 'AA0E73D2'.\n"
msgstr ""

#: ../duplicity/argparse311.py:291
msgid "usage: "
msgstr ""

#: ../duplicity/argparse311.py:761
#, python-format
msgid "argument %(argument_name)s: %(message)s"
msgstr ""

#: ../duplicity/argparse311.py:870
msgid ".__call__() not defined"
msgstr ""

#: ../duplicity/argparse311.py:1115
#, python-format
msgid "conflicting subparser: %s"
msgstr ""

#: ../duplicity/argparse311.py:1118
#, python-format
msgid "conflicting subparser alias: %s"
msgstr ""

#: ../duplicity/argparse311.py:1152
#, python-format
msgid "unknown parser %(parser_name)r (choices: %(choices)s)"
msgstr ""

#: ../duplicity/argparse311.py:1215
#, python-format
msgid "argument \"-\" with mode %r"
msgstr ""

#: ../duplicity/argparse311.py:1223
#, python-format
msgid "can't open '%(filename)s': %(error)s"
msgstr ""

#: ../duplicity/argparse311.py:1427
#, python-format
msgid "cannot merge actions - two groups are named %r"
msgstr ""

#: ../duplicity/argparse311.py:1462
msgid "'required' is an invalid argument for positionals"
msgstr ""

#: ../duplicity/argparse311.py:1483
#, python-format
msgid "invalid option string %(option)r: must start with a character %(prefix_chars)r"
msgstr ""

#: ../duplicity/argparse311.py:1500
#, python-format
msgid "dest= is required for options like %r"
msgstr ""

#: ../duplicity/argparse311.py:1517
#, python-format
msgid "invalid conflict_resolution value: %r"
msgstr ""

#: ../duplicity/argparse311.py:1534
#, python-format
msgid "conflicting option string: %s"
msgid_plural "conflicting option strings: %s"
msgstr[0] ""
msgstr[1] ""

#: ../duplicity/argparse311.py:1595
msgid "mutually exclusive arguments must be optional"
msgstr ""

#: ../duplicity/argparse311.py:1670
msgid "positional arguments"
msgstr ""

#: ../duplicity/argparse311.py:1689
msgid "show this help message and exit"
msgstr ""

#: ../duplicity/argparse311.py:1721
msgid "cannot have multiple subparser arguments"
msgstr ""

#: ../duplicity/argparse311.py:1769 ../duplicity/argparse311.py:2264
#, python-format
msgid "unrecognized arguments: %s"
msgstr ""

#: ../duplicity/argparse311.py:1868
#, python-format
msgid "not allowed with argument %s"
msgstr ""

#: ../duplicity/argparse311.py:1912 ../duplicity/argparse311.py:1926
#, python-format
msgid "ignored explicit argument %r"
msgstr ""

#: ../duplicity/argparse311.py:2030
#, python-format
msgid "the following arguments are required: %s"
msgstr ""

#: ../duplicity/argparse311.py:2042
#, python-format
msgid "one of the arguments %s is required"
msgstr ""

#: ../duplicity/argparse311.py:2083
msgid "expected one argument"
msgstr ""

#: ../duplicity/argparse311.py:2084
msgid "expected at most one argument"
msgstr ""

#: ../duplicity/argparse311.py:2085
msgid "expected at least one argument"
msgstr ""

#: ../duplicity/argparse311.py:2089
#, python-format
msgid "expected %s argument"
msgid_plural "expected %s arguments"
msgstr[0] ""
msgstr[1] ""

#: ../duplicity/argparse311.py:2143
#, python-format
msgid "ambiguous option: %(option)s could match %(matches)s"
msgstr ""

#: ../duplicity/argparse311.py:2207
#, python-format
msgid "unexpected option string: %s"
msgstr ""

#: ../duplicity/argparse311.py:2402
#, python-format
msgid "%r is not callable"
msgstr ""

#: ../duplicity/argparse311.py:2419
#, python-format
msgid "invalid %(type)s value: %(value)r"
msgstr ""

#: ../duplicity/argparse311.py:2429
#, python-format
msgid "invalid choice: %(value)r (choose from %(choices)s)"
msgstr ""

#: ../duplicity/argparse311.py:2505
#, python-format
msgid "%(prog)s: error: %(message)s\n"
msgstr ""

