msgid ""
msgstr ""
"Project-Id-Version: duplicity\n"
"Report-Msgid-Bugs-To: Kenneth Loafman <kenneth@loafman.com>\n"
"POT-Creation-Date: 2023-12-27 10:21-0600\n"
"PO-Revision-Date: 2023-12-27 17:28\n"
"Last-Translator: \n"
"Language-Team: Rսssian, Սkraine\n"
"Language: ru_UA\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=4; plural=((n%10==1 && n%100!=11) ? 0 : ((n%10 >= 2 && n%10 <=4 && (n%100 < 12 || n%100 > 14)) ? 1 : ((n%10 == 0 || (n%10 >= 5 && n%10 <=9)) || (n%100 >= 11 && n%100 <= 14)) ? 2 : 3));\n"
"X-Crowdin-Project: duplicity\n"
"X-Crowdin-Project-ID: 539508\n"
"X-Crowdin-Language: ru-UA\n"
"X-Crowdin-File: /main/po/duplicity.pot\n"
"X-Crowdin-File-ID: 6\n"

#: ../bin/duplicity:76
msgid "INT intercepted...exiting."
msgstr "Перехват INT...выполняется выход."

#: ../bin/duplicity:84
#, python-format
msgid "GPG error detail: %s"
msgstr "Подробности ошибки GPG: %s"

#: ../bin/duplicity:91
#, python-format
msgid "User error detail: %s"
msgstr "Сведения ошибки пользователя: %s"

#: ../bin/duplicity:98
#, python-format
msgid "Backend error detail: %s"
msgstr "Подробности об ошибке в заглушке: %s"

#: ../duplicity/tempdir.py:157
#, python-format
msgid "Using temporary directory %s"
msgstr "Используется временный каталог %s"

#: ../duplicity/tempdir.py:201
#, python-format
msgid "Registering (mktemp) temporary file %s"
msgstr "Регистрация (mktemp) временного файла %s"

#: ../duplicity/tempdir.py:227
#, python-format
msgid "Registering (mkstemp) temporary file %s"
msgstr "Регистрация (mkstemp) временного файла %s"

#: ../duplicity/tempdir.py:259
#, python-format
msgid "Forgetting temporary file %s"
msgstr "Удаление временного файла %s"

#: ../duplicity/tempdir.py:262
#, python-format
msgid "Attempt to forget unknown tempfile %s - this is probably a bug."
msgstr "Попытка удалить неизвестный временный файл %s - похоже, что это ошибка в программе."

#: ../duplicity/tempdir.py:281
#, python-format
msgid "Removing still remembered temporary file %s"
msgstr "Удаление всё ещё нужного временного файла %s"

#: ../duplicity/tempdir.py:284
#, python-format
msgid "Cleanup of temporary file %s failed"
msgstr "Не удалось очистить временный файл %s"

#: ../duplicity/tempdir.py:290
#, python-format
msgid "Cleanup of temporary directory %s failed - this is probably a bug."
msgstr "Не удалось очистить временный каталог %s - похоже, что это ошибка в программе."

#: ../duplicity/backend.py:92
#, python-format
msgid "Import of %s %s"
msgstr "Импортирование %s %s"

#: ../duplicity/backend.py:197
#, python-format
msgid "Could not initialize backend: %s"
msgstr "Невозможно инициализиовать внутренний интерфейс: %s"

#: ../duplicity/backend.py:388
#, python-format
msgid "Backtrace of previous error: %s"
msgstr ""

#: ../duplicity/backend.py:407
#, python-format
msgid "Giving up after %s attempts. %s: %s"
msgstr ""

#: ../duplicity/backend.py:413
#, python-format
msgid "Attempt of %s Nr. %s failed. %s: %s"
msgstr ""

#: ../duplicity/backend.py:512
#, python-format
msgid "Reading results of '%s'"
msgstr "Чтение результата '%s'"

#: ../duplicity/backend.py:539
#, python-format
msgid "Writing %s"
msgstr "Записывается %s"

#: ../duplicity/backend.py:580
#, python-format
msgid "File %s not found locally after get from backend"
msgstr ""

#: ../duplicity/manifest.py:95
#, python-format
msgid "Fatal Error: Backup source host has changed.\n"
"Current hostname: %s\n"
"Previous hostname: %s"
msgstr "Критическая ошибка: Узел источника резервной копии изменён.\n"
"Текущий узел: %s\n"
"Предыдущий узел: %s"

#: ../duplicity/manifest.py:102
msgid "Fatal Error: Backup source directory has changed.\n"
msgstr ""

#: ../duplicity/manifest.py:115
msgid "Aborting because you may have accidentally tried to backup two different data sets to the same remote location, or using the same archive directory.  If this is not a mistake, use the --allow-source-mismatch switch to avoid seeing this message"
msgstr "Прекращение в связи с тем, что вы можете случайно попытаться создать резервные копии двух отличающихся наборов данных, по одному адресу, в одно и тоже удалённое расположение.  Если это ошибка, используйте параметр --allow-source-mismatch для скрытия этого сообщения"

#: ../duplicity/manifest.py:221
#, python-format
msgid "Found manifest volume %s"
msgstr ""

#: ../duplicity/manifest.py:228
#, python-format
msgid "Found %s volumes in manifest"
msgstr ""

#: ../duplicity/manifest.py:249
msgid "Manifest file '{self.fh.base if self.fh else ''}' is corrupt: "
msgstr ""

#: ../duplicity/manifest.py:268
msgid "Manifests not equal because different volume numbers"
msgstr "Манифесты не одинаковы в связи с отличающимися номерами томов"

#: ../duplicity/manifest.py:273
msgid "Manifests not equal because volume lists differ"
msgstr "Манифесты не одинаковы в связи с отличающимися списками томов"

#: ../duplicity/manifest.py:277
msgid "Manifests not equal because hosts or directories differ"
msgstr "Манифесты не одинаковы в связи с отличающимися узлами или каталогами"

#: ../duplicity/manifest.py:438
msgid "Warning, found extra Volume identifier"
msgstr "Внимание, найден дополнительный идентификатор тома"

#: ../duplicity/manifest.py:464
msgid "Other is not VolumeInfo"
msgstr "Другой не является VolumeInfo"

#: ../duplicity/manifest.py:467
msgid "Volume numbers don't match"
msgstr "Номера томов не соответствуют"

#: ../duplicity/manifest.py:470
msgid "start_indicies don't match"
msgstr "start_indicies не соответствует"

#: ../duplicity/manifest.py:473
msgid "end_index don't match"
msgstr "end_index не соответствует"

#: ../duplicity/manifest.py:478
msgid "Hashes don't match"
msgstr "Хэши не совпадают"

#: ../duplicity/util.py:105 ../duplicity/dup_main.py:906
#, python-format
msgid "IGNORED_ERROR: Warning: ignoring error as requested: %s: %s"
msgstr "IGNORED_ERROR: Внимание: пропуск ошибки, как было обозначено в запросе: %s: %s"

#: ../duplicity/util.py:170
#, python-format
msgid "Releasing lockfile %s"
msgstr ""

#: ../duplicity/backends/pydrivebackend.py:203
#, python-format
msgid "PyDrive backend: multiple files called '%s'."
msgstr ""

#: ../duplicity/backends/multibackend.py:100
#, python-format
msgid "MultiBackend: Could not parse query string %s: %s "
msgstr ""

#: ../duplicity/backends/multibackend.py:110
#, python-format
msgid "MultiBackend: Invalid query string %s: more than one value for %s"
msgstr ""

#: ../duplicity/backends/multibackend.py:116
#, python-format
msgid "MultiBackend: Invalid query string %s: unknown parameter %s"
msgstr ""

#: ../duplicity/backends/multibackend.py:167
#: ../duplicity/backends/multibackend.py:174
#, python-format
msgid "MultiBackend: illegal value for %s: %s"
msgstr ""

#: ../duplicity/backends/multibackend.py:186
#, python-format
msgid "MultiBackend: Url %s"
msgstr ""

#: ../duplicity/backends/multibackend.py:189
#, python-format
msgid "MultiBackend: Could not load config file %s: %s "
msgstr ""

#: ../duplicity/backends/multibackend.py:196
#, python-format
msgid "MultiBackend: use store %s"
msgstr ""

#: ../duplicity/backends/multibackend.py:200
#, python-format
msgid "MultiBackend: set env %s = %s"
msgstr ""

#: ../duplicity/backends/multibackend.py:214
#, python-format
msgid "Multibackend: register affinity for prefix %s"
msgstr ""

#: ../duplicity/backends/multibackend.py:257
#, python-format
msgid "MultiBackend: _put: write to store #%s (%s)"
msgstr ""

#: ../duplicity/backends/multibackend.py:272
#, python-format
msgid "MultiBackend: failed to write to store #%s (%s), try #%s, Exception: %s"
msgstr ""

#: ../duplicity/backends/multibackend.py:286
#, python-format
msgid "MultiBackend: failed to write %s. Aborting process."
msgstr ""

#: ../duplicity/backends/multibackend.py:294
#, python-format
msgid "MultiBackend: failed to write %s. Tried all backing stores and none succeeded"
msgstr ""

#: ../duplicity/backends/multibackend.py:315
#, python-format
msgid "MultiBackend: failed to get %s to %s from %s"
msgstr ""

#: ../duplicity/backends/multibackend.py:320
#, python-format
msgid "MultiBackend: failed to get %s. Tried all backing stores and none succeeded"
msgstr ""

#: ../duplicity/backends/multibackend.py:330
#, python-format
msgid "MultiBackend: %s: %d files"
msgstr ""

#: ../duplicity/backends/multibackend.py:334
msgid "Exception during list of {s.backend.parsed_url.strip_auth()}: "
msgstr ""

#: ../duplicity/backends/multibackend.py:342
#, python-format
msgid "MultiBackend: combined list: %s"
msgstr ""

#: ../duplicity/backends/multibackend.py:371
#: ../duplicity/backends/multibackend.py:398
#, python-format
msgid "MultiBackend: failed to delete %s. Tried all backing stores and none succeeded"
msgstr ""

#: ../duplicity/backends/giobackend.py:108
#, python-format
msgid "Connection failed, please check your password: %s"
msgstr "Не удалось подключиться, проверьте пароль: %s"

#: ../duplicity/backends/onedrivebackend.py:90
#, python-format
msgid "Attempt of initialize_oauth2_session Nr. %s failed. %s: %s"
msgstr ""

#: ../duplicity/backends/webdavbackend.py:67
msgid "Missing socket or ssl python modules."
msgstr ""

#: ../duplicity/backends/webdavbackend.py:87
#, python-format
msgid "Cacert database file '%s' is not readable."
msgstr ""

#: ../duplicity/backends/webdavbackend.py:149
#, python-format
msgid "Using WebDAV host %s port %s"
msgstr ""

#: ../duplicity/backends/webdavbackend.py:150
#, python-format
msgid "Using WebDAV directory %s"
msgstr ""

#: ../duplicity/backends/webdavbackend.py:180
#, python-format
msgid "WebDAV create connection on '%s'"
msgstr ""

#: ../duplicity/backends/webdavbackend.py:191
#, python-format
msgid "WebDAV Unknown URI scheme: %s"
msgstr ""

#: ../duplicity/backends/webdavbackend.py:210
#, python-format
msgid "WebDAV %s %s request with headers: %s "
msgstr ""

#: ../duplicity/backends/webdavbackend.py:211
#: ../duplicity/backends/webdavbackend.py:234
#, python-format
msgid "WebDAV data length: %s "
msgstr ""

#: ../duplicity/backends/webdavbackend.py:214
#, python-format
msgid "WebDAV response status %s with reason '%s'."
msgstr ""

#: ../duplicity/backends/webdavbackend.py:220
#, python-format
msgid "WebDAV redirect to: %s "
msgstr ""

#: ../duplicity/backends/webdavbackend.py:222
msgid "WebDAV redirected 10 times. Giving up."
msgstr ""

#: ../duplicity/backends/webdavbackend.py:227
msgid "WebDAV missing location header in redirect response."
msgstr ""

#: ../duplicity/backends/webdavbackend.py:232
msgid "WebDAV retry request with authentification headers."
msgstr ""

#: ../duplicity/backends/webdavbackend.py:233
#, python-format
msgid "WebDAV %s %s request2 with headers: %s "
msgstr ""

#: ../duplicity/backends/webdavbackend.py:237
#, python-format
msgid "WebDAV response2 status %s with reason '%s'."
msgstr ""

#: ../duplicity/backends/webdavbackend.py:256
msgid "python-kerberos needed to use kerberos                           authorization, falling back to basic auth."
msgstr ""

#: ../duplicity/backends/webdavbackend.py:264
#, python-format
msgid "Kerberos authorization failed: %s.                          Falling back to basic auth."
msgstr ""

#: ../duplicity/backends/webdavbackend.py:365
#, python-format
msgid "Creating missing directory %s"
msgstr ""

#: ../duplicity/backends/webdavbackend.py:369
#, python-format
msgid "WebDAV MKCOL %s failed: %s %s"
msgstr ""

#: ../duplicity/backends/webdavbackend.py:381
#, python-format
msgid "WebDAV path decoding and translation: %s -> %s"
msgstr ""

#: ../duplicity/backends/webdavbackend.py:421
#, python-format
msgid "WebDAV GET Bad status code %s reason %s."
msgstr ""

#: ../duplicity/backends/webdavbackend.py:442
#, python-format
msgid "WebDAV PUT Bad status code %s reason %s."
msgstr ""

#: ../duplicity/backends/webdavbackend.py:461
#, python-format
msgid "WebDAV DEL Bad status code %s reason %s."
msgstr ""

#. Used in usage help to represent a Unix-style path name. Example:
#. --archive-dir <path>
#: ../duplicity/cli_data.py:102 ../duplicity/cli_data.py:162
#: ../duplicity/cli_data.py:196 ../duplicity/cli_data.py:243
#: ../duplicity/cli_data.py:346 ../duplicity/cli_data.py:364
#: ../duplicity/cli_data.py:524 ../duplicity/cli_data.py:706
#: ../duplicity/cli_data.py:932
msgid "path"
msgstr "путь"

#: ../duplicity/cli_data.py:115
msgid "Hot|Cool|Archive"
msgstr ""

#. Used in usage help to represent a desired number of
#. something. Example:
#. --num-retries <number>
#: ../duplicity/cli_data.py:120 ../duplicity/cli_data.py:126
#: ../duplicity/cli_data.py:134 ../duplicity/cli_data.py:168
#: ../duplicity/cli_data.py:432 ../duplicity/cli_data.py:448
#: ../duplicity/cli_data.py:495 ../duplicity/cli_data.py:512
#: ../duplicity/cli_data.py:518 ../duplicity/cli_data.py:536
#: ../duplicity/cli_data.py:602 ../duplicity/cli_data.py:610
#: ../duplicity/cli_data.py:662 ../duplicity/cli_data.py:743
#: ../duplicity/cli_data.py:919
msgid "number"
msgstr "количество"

#. Used in usage help. Example:
#. --timeout <seconds>
#: ../duplicity/cli_data.py:146 ../duplicity/cli_data.py:713
#: ../duplicity/cli_data.py:945
msgid "seconds"
msgstr "секунды"

#. Used in usage help to represent an ID for a GnuPG key. Example:
#. --encrypt-key <gpg_key_id>
#: ../duplicity/cli_data.py:184 ../duplicity/cli_data.py:190
#: ../duplicity/cli_data.py:358 ../duplicity/cli_data.py:669
#: ../duplicity/cli_data.py:911
msgid "gpg-key-id"
msgstr ""

#. Used in usage help to represent a "glob" style pattern for
#. matching one or more files, as described in the documentation.
#. Example:
#. --exclude <shell_pattern>
#: ../duplicity/cli_data.py:201 ../duplicity/cli_data.py:386
#: ../duplicity/cli_data.py:950
msgid "shell_pattern"
msgstr ""

#. Used in usage help to represent the name of a file. Example:
#. --log-file <filename>
#: ../duplicity/cli_data.py:213 ../duplicity/cli_data.py:219
#: ../duplicity/cli_data.py:279 ../duplicity/cli_data.py:392
#: ../duplicity/cli_data.py:908
msgid "filename"
msgstr "имя файла"

#. Used in usage help to represent a time spec for a previous
#. point in time, as described in the documentation. Example:
#. duplicity remove-older-than time [options] target_url
#: ../duplicity/cli_data.py:225 ../duplicity/cli_data.py:549
#: ../duplicity/cli_data.py:976
msgid "time"
msgstr "время"

#: ../duplicity/cli_data.py:237 ../duplicity/cli_data.py:398
msgid "regex"
msgstr ""

#: ../duplicity/cli_data.py:340
msgid "interval"
msgstr ""

#. Used in usage help. (Should be consistent with the "Options:"
#. header.) Example:
#. duplicity [full|incremental] [options] source_path target_url
#: ../duplicity/cli_data.py:352 ../duplicity/cli_data.py:506
#: ../duplicity/cli_data.py:555 ../duplicity/cli_data.py:685
#: ../duplicity/cli_data.py:923 ../duplicity/argparse311.py:1671
msgid "options"
msgstr "параметры"

#: ../duplicity/cli_data.py:381
msgid "imap_mailbox"
msgstr ""

#: ../duplicity/cli_data.py:406
msgid "If set, an extra file with statistics in json format will be stored with each backup. It includes the statistics printed out on stdout by default. With 'collection-status' it returs these stats."
msgstr ""

#: ../duplicity/cli_data.py:414
msgid "file_descriptor"
msgstr ""

#: ../duplicity/cli_data.py:421
msgid "log_filename"
msgstr ""

#: ../duplicity/cli_data.py:454
msgid "backup name"
msgstr "название резервной копии"

#: ../duplicity/cli_data.py:561
msgid "s3_endpoint_url"
msgstr ""

#: ../duplicity/cli_data.py:629
msgid "s3_kms_key_id"
msgstr ""

#: ../duplicity/cli_data.py:635
msgid "s3_kms_grant"
msgstr ""

#: ../duplicity/cli_data.py:641
msgid "s3_region_name"
msgstr ""

#: ../duplicity/cli_data.py:647
msgid "policy"
msgstr ""

#. noun
#: ../duplicity/cli_data.py:652 ../duplicity/cli_data.py:657
#: ../duplicity/cli_data.py:897
msgid "command"
msgstr "команда"

#: ../duplicity/cli_data.py:692
msgid "pem formatted bundle of certificate authorities"
msgstr ""

#: ../duplicity/cli_data.py:697
msgid "path to a folder with certificate authority files"
msgstr ""

#. abbreviation for "character" (noun)
#: ../duplicity/cli_data.py:719 ../duplicity/cli_data.py:895
msgid "char"
msgstr "символ"

#: ../duplicity/cli_data.py:732
msgid "verb"
msgstr ""

#: ../duplicity/cli_data.py:750
msgid "extra headers for Webdav, like 'Cookie,name=value'"
msgstr ""

#. Used in usage help to represent a Unix-style path name. Example:
#. rsync://user[:password]@other_host[:port]//absolute_path
#: ../duplicity/cli_data.py:886
msgid "absolute_path"
msgstr "полный_путь"

#. Used in usage help. Example:
#. tahoe://alias/some_dir
#: ../duplicity/cli_data.py:889
msgid "alias"
msgstr "псевдоним"

#. Used in help to represent a "bucket name" for Amazon Web
#. Services' Simple Storage Service (S3). Example:
#. s3://other.host/bucket_name[/prefix]
#: ../duplicity/cli_data.py:893
msgid "bucket_name"
msgstr ""

#. Used in usage help to represent the name of a container in
#. Amazon Web Services' Cloudfront. Example:
#. cf+http://container_name
#: ../duplicity/cli_data.py:901
msgid "container_name"
msgstr ""

#. noun
#: ../duplicity/cli_data.py:903
msgid "count"
msgstr "количество"

#. Used in usage help to represent the name of a file directory
#: ../duplicity/cli_data.py:905
msgid "directory"
msgstr "каталог"

#. Used in usage help, e.g. to represent the name of a code
#. module. Example:
#. rsync://user[:password]@other.host[:port]::/module/some_dir
#: ../duplicity/cli_data.py:915
msgid "module"
msgstr "модуль"

#. Used in usage help to represent an internet hostname. Example:
#. ftp://user[:password]@other.host[:port]/some_dir
#: ../duplicity/cli_data.py:926
msgid "other.host"
msgstr ""

#. Used in usage help. Example:
#. ftp://user[:password]@other.host[:port]/some_dir
#: ../duplicity/cli_data.py:929
msgid "password"
msgstr "пароль"

#. Used in usage help to represent a TCP port number. Example:
#. ftp://user[:password]@other.host[:port]/some_dir
#: ../duplicity/cli_data.py:935
msgid "port"
msgstr "порт"

#. Used in usage help. This represents a string to be used as a
#. prefix to names for backup files created by Duplicity. Example:
#. s3://other.host/bucket_name[/prefix]
#: ../duplicity/cli_data.py:939
msgid "prefix"
msgstr "префикс"

#. Used in usage help to represent a Unix-style path name. Example:
#. rsync://user[:password]@other.host[:port]/relative_path
#: ../duplicity/cli_data.py:942
msgid "relative_path"
msgstr "относительный_путь"

#. Used in usage help to represent the name of a single file
#. directory or a Unix-style path to a directory. Example:
#. file:///some_dir
#: ../duplicity/cli_data.py:954
msgid "some_dir"
msgstr "некоторый_каталог"

#. Used in usage help to represent the name of a single file
#. directory or a Unix-style path to a directory where files will be
#. coming FROM. Example:
#. duplicity [full|incremental] [options] source_path target_url
#: ../duplicity/cli_data.py:959
msgid "source_path"
msgstr ""

#. Used in usage help to represent a URL files will be coming
#. FROM. Example:
#. duplicity [restore] [options] source_url target_dir
#: ../duplicity/cli_data.py:963
msgid "source_url"
msgstr ""

#. Used in usage help to represent the name of a single file
#. directory or a Unix-style path to a directory. where files will be
#. going TO. Example:
#. duplicity [restore] [options] source_url target_dir
#: ../duplicity/cli_data.py:968
msgid "target_dir"
msgstr ""

#. Used in usage help to represent a URL files will be going TO.
#. Example:
#. duplicity [full|incremental] [options] source_path target_url
#: ../duplicity/cli_data.py:972
msgid "target_url"
msgstr ""

#. Used in usage help to represent a user name (i.e. login).
#. Example:
#. ftp://user[:password]@other.host[:port]/some_dir
#: ../duplicity/cli_data.py:980
msgid "user"
msgstr "пользователь"

#. account id for b2. Example: b2://account_id@bucket/
#: ../duplicity/cli_data.py:982
msgid "account_id"
msgstr ""

#. application_key for b2.
#. Example: b2://account_id:application_key@bucket/
#: ../duplicity/cli_data.py:985
msgid "application_key"
msgstr ""

#. remote name for rclone.
#. Example: rclone://remote:/some_dir
#: ../duplicity/cli_data.py:988 ../duplicity/dup_collections.py:565
msgid "remote"
msgstr "удалённая"

#: ../duplicity/cli_data.py:992
msgid "Backends and their URL formats:"
msgstr "Заглушки и формат их URL:"

#: ../duplicity/diffdir.py:102 ../duplicity/diffdir.py:401
#, python-format
msgid "Error %s getting delta for %s"
msgstr "Ошибка %s при получении различий для %s"

#: ../duplicity/diffdir.py:116
#, python-format
msgid "Getting delta of %s and %s"
msgstr "Приём дельты %s и %s"

#: ../duplicity/diffdir.py:160
#, python-format
msgid "A %s"
msgstr "Д %s"

#: ../duplicity/diffdir.py:168
#, python-format
msgid "M %s"
msgstr "И %s"

#: ../duplicity/diffdir.py:191
#, python-format
msgid "Comparing %s and %s"
msgstr "Сравнение %s и %s"

#: ../duplicity/diffdir.py:204
#, python-format
msgid "D %s"
msgstr "У %s"

#: ../duplicity/librsync.py:194
msgid "basis_file must be a (true) file or an object whose file attribute is the underlying true file object"
msgstr ""

#: ../duplicity/dup_time.py:54
#, python-format
msgid "Bad interval string \"%s\"\n\n"
"Intervals are specified like 2Y (2 years) or 2h30m (2.5 hours).  The\n"
"allowed special characters are s, m, h, D, W, M, and Y.  See the man\n"
"page for more information."
msgstr "Строка с недопустимым интервалом \"%s\"\n\n"
"Интервалы задаются на подобии 2Y (2 года) или 2h30m (2.5 часа).\n"
"Допустимые особые символы s (с.), m (м.), h (ч.), D(Д.), W (Н.), M (М.) и Y (Г.).  \n"
"Обратитесь к руководству пользователя (man) для получения дополнительных сведений."

#: ../duplicity/dup_time.py:63
#, python-format
msgid "Bad time string \"%s\"\n\n"
"The acceptible time strings are intervals (like \"3D64s\"), w3-datetime\n"
"strings, like \"2002-04-26T04:22:01-07:00\" (strings like\n"
"\"2002-04-26T04:22:01\" are also acceptable - duplicity will use the\n"
"current time zone), or ordinary dates like 2/4/1997 or 2001-04-23\n"
"(various combinations are acceptable, but the month always precedes\n"
"the day)."
msgstr "Строка с недопустимым временем \"%s\"\n\n"
"Допускается задание интервалов времени (например \"3D64s\"), строки \n"
"даты/времени формата w3, например \"2002-04-26T04:22:01-07:00\" (строки типа\n"
"\"2002-04-26T04:22:01\" также допустимы - duplicity будет использовать\n"
"текущую временную зону) или обычные даты, например 2/4/1997 или 2001-04-23\n"
"(допустимы различные комбинации, но месяц всегда предшествует дню)."

#: ../duplicity/cli_main.py:155
msgid "No valid action found. Will imply 'backup' because a path source was given and target is a url location."
msgstr ""

#: ../duplicity/cli_main.py:163
msgid "No valid action found. Will imply 'restore' because url source was given and target is a local path."
msgstr ""

#: ../duplicity/cli_main.py:170
#, python-brace-format
msgid "Invalid '{remainder[0]}' action and cannot be implied from the "
msgstr ""

#: ../duplicity/cli_main.py:291
#, python-brace-format
msgid "GPG binary is {config.gpg_binary}, version {gpg_version}"
msgstr ""

#: ../duplicity/cli_main.py:327
#, python-brace-format
msgid "Using archive dir: {config.archive_dir_path.uc_name}"
msgstr ""

#: ../duplicity/cli_main.py:328
#, python-brace-format
msgid "Using backup name: {config.backup_name}"
msgstr ""

#: ../duplicity/dup_main.py:113
msgid "Reuse configured PASSPHRASE as SIGN_PASSPHRASE"
msgstr "Повторное использование настроенного PASSPHRASE как SIGN_PASSPHRASE"

#: ../duplicity/dup_main.py:124
msgid "Reuse configured SIGN_PASSPHRASE as PASSPHRASE"
msgstr "Повторное использование настроенного SIGN_PASSPHRASE как PASSPHRASE"

#: ../duplicity/dup_main.py:168
msgid "PASSPHRASE variable not set, asking user."
msgstr "Переменная PASSPHRASE не назначена, выполняется запрос пользователя."

#: ../duplicity/dup_main.py:193
msgid "Retype passphrase for signing key to confirm: "
msgstr "Введите повторно кодовую фразу для подписывающего ключа: "

#: ../duplicity/dup_main.py:195
msgid "Retype passphrase for decryption to confirm: "
msgstr ""

#: ../duplicity/dup_main.py:199
msgid "First and second passphrases do not match!  Please try again."
msgstr "Первая и вторая кодовая фраза не совпадают! Пожалуйста, повторите снова."

#: ../duplicity/dup_main.py:210
msgid "Cannot use empty passphrase with symmetric encryption!  Please try again."
msgstr "Невозможно использовать пустую кодовую фразу с симметричным шифрованием!  Пожалуйста, повторите снова."

#: ../duplicity/dup_main.py:270
#, python-format
msgid "File %s complete in backup set.\n"
"Continuing restart on file %s."
msgstr "Файл %s уже имеется в наборе резервного копирования.\n"
"Продолжение перезапуска на файле %s."

#: ../duplicity/dup_main.py:280
#, python-format
msgid "File %s missing in backup set.\n"
"Continuing restart on file %s."
msgstr "Файл %s отсутствует в наборе резервного копирования.\n"
"Продолжение перезапуска на файле %s."

#: ../duplicity/dup_main.py:335
#, python-format
msgid "%s Remote filesize %d for %s does not match local size %d, retrying."
msgstr ""

#: ../duplicity/dup_main.py:342
#, python-format
msgid "File %s was corrupted during upload."
msgstr "Файл %s был повреждён во время выгрузки."

#: ../duplicity/dup_main.py:382
msgid "Restarting backup, but current encryption settings do not match original settings"
msgstr "Перезапуск резервного копирования, но настройки текущего шифрования не соответствуют исходным настройкам"

#: ../duplicity/dup_main.py:404
msgid "Skipping encryption validation due to glacier/deep storage"
msgstr ""

#: ../duplicity/dup_main.py:408
#, python-format
msgid "Restarting after volume %s, file %s, block %s"
msgstr ""

#: ../duplicity/dup_main.py:471
msgid "Skipped volume upload, as effectivly nothing has changed"
msgstr ""

#: ../duplicity/dup_main.py:485
#, python-format
msgid "Processed volume %d"
msgstr ""

#: ../duplicity/dup_main.py:653
msgid "Fatal Error: Unable to start incremental backup.  Old signatures not found and incremental specified"
msgstr "Фатальная ошибка: Не удалось начать пошаговое резервное копирование. Старая сигнатура не найдена и указан пошаговый режим"

#: ../duplicity/dup_main.py:659
msgid "No signatures found, switching to full backup."
msgstr "Сигнатуры не найдены, переключение на полную резервную копию."

#: ../duplicity/dup_main.py:673
msgid "Backup Statistics"
msgstr "Статистика резервного копирования"

#: ../duplicity/dup_main.py:813
#, python-format
msgid "%s not found in archive - no files restored."
msgstr "%s не найден в архиве, нет восстановленных файлов."

#: ../duplicity/dup_main.py:817
msgid "No files found in archive - nothing restored."
msgstr "Ничего не найдено в архиве - ничего не восстановлено."

#: ../duplicity/dup_main.py:853
#, python-format
msgid "Processed volume %d of %d"
msgstr "Обработан том %d из %d"

#: ../duplicity/dup_main.py:896
#, python-format
msgid "Invalid data - %s hash mismatch for file:"
msgstr "Недопустимые данные - %s hash не соответствует файлу:"

#: ../duplicity/dup_main.py:898
#, python-format
msgid "Calculated hash: %s"
msgstr "Вычисленный хэш: %s"

#: ../duplicity/dup_main.py:899
#, python-format
msgid "Manifest hash: %s"
msgstr "Хеш манифеста: %s"

#: ../duplicity/dup_main.py:952
#, python-format
msgid "Volume was signed by key %s, not %s"
msgstr "Том был подписан ключом %s, а не %s"

#: ../duplicity/dup_main.py:984
#, python-format
msgid "Verify complete: %s, %s."
msgstr "Проверка завершена: %s, %s."

#: ../duplicity/dup_main.py:985
#, python-format
msgid "%d file(s) compared"
msgstr ""

#: ../duplicity/dup_main.py:985
#, python-format
msgid "%d difference(s) found"
msgstr ""

#: ../duplicity/dup_main.py:1004
msgid "No extraneous files found, nothing deleted in cleanup."
msgstr "Посторонних файлов не найдено, при очистке ничего не удалено."

#: ../duplicity/dup_main.py:1019
msgid "Found the following file(s) to delete:"
msgstr ""

#: ../duplicity/dup_main.py:1023
msgid "Run duplicity again with the --force option to actually delete."
msgstr "Запустите duplicity ещё раз с ключом --force чтобы удалить на самом деле."

#: ../duplicity/dup_main.py:1069
msgid "There are backup set(s) at time(s):"
msgstr "Есть резервные копии за следующие даты:"

#: ../duplicity/dup_main.py:1071
msgid "Which can't be deleted because newer sets depend on them."
msgstr "Какие не могут быть удалены из-за новых наборов зависящих от них."

#: ../duplicity/dup_main.py:1078
msgid "Current active backup chain is older than specified time.  However, it will not be deleted.  To remove all your backups, manually purge the repository."
msgstr "Текущая активная цепочка резервных копий старее чем указанное время.  Те не менее, она не будет удалена. Чтобы удалить все резервные копии, вручную очистите хранилище."

#: ../duplicity/dup_main.py:1096
msgid "No old backup sets found, nothing deleted."
msgstr "Старые резервные копии не найдены, ничего не удалено."

#: ../duplicity/dup_main.py:1099
msgid "Deleting backup chain(s) at time:"
msgstr ""

#: ../duplicity/dup_main.py:1108
#, python-format
msgid "Deleting any incremental signature chain rooted at %s"
msgstr ""

#: ../duplicity/dup_main.py:1110
#, python-format
msgid "Deleting any incremental backup chain rooted at %s"
msgstr ""

#: ../duplicity/dup_main.py:1113
#, python-format
msgid "Deleting complete signature chain %s"
msgstr "Удаление всей цепочки подписей %s"

#: ../duplicity/dup_main.py:1115
#, python-format
msgid "Deleting complete backup chain %s"
msgstr "Удаление полной цепочки резервных копий  %s"

#: ../duplicity/dup_main.py:1122
msgid "Found old backup chain(s) at the following time:"
msgstr ""

#: ../duplicity/dup_main.py:1126
msgid "Rerun command with --force option to actually delete."
msgstr ""

#: ../duplicity/dup_main.py:1229
#, python-format
msgid "Deleting local %s (not authoritative at backend)."
msgstr "Удаление локального %s (недостаточно надёжный во внутреннем интерфейсе)."

#: ../duplicity/dup_main.py:1233
#, python-format
msgid "Unable to delete %s: %s"
msgstr "Невозможно удалить %s: %s"

#: ../duplicity/dup_main.py:1267 ../duplicity/dup_temp.py:296
#, python-format
msgid "Failed to read %s: %s"
msgstr "Не удалось прочитать %s: %s"

#: ../duplicity/dup_main.py:1279
#, python-format
msgid "Copying %s to local cache."
msgstr "Копируется %s в локальный кэш."

#: ../duplicity/dup_main.py:1327
msgid "Local and Remote metadata are synchronized, no sync needed."
msgstr "Локальные и удалённые метаданные синхронизированы, синхронизация не требуется."

#: ../duplicity/dup_main.py:1332
msgid "Synchronizing remote metadata to local cache..."
msgstr "Синхронизация удалённых метаданных с локальными временными файлами..."

#: ../duplicity/dup_main.py:1346
msgid "Sync would copy the following from remote to local:"
msgstr "Синхронизация скопирует это из удаленного места в локальное:"

#: ../duplicity/dup_main.py:1352
msgid "Sync would remove the following spurious local files:"
msgstr "Синхронизация удалит следующие  неизвестные файлы:"

#: ../duplicity/dup_main.py:1398
msgid "Unable to get free space on temp."
msgstr "Не удалось узнать объем доступного пространства во временном каталоге."

#: ../duplicity/dup_main.py:1405
#, python-format
msgid "Temp space has %d available, backup needs approx %d."
msgstr "Во временно каталоге доступного %d, для резервного копирования нужно примерно %d."

#: ../duplicity/dup_main.py:1409
#, python-format
msgid "Temp has %d available, backup will use approx %d."
msgstr "Во временном каталоге доступно %d, для резервного копирования будет использовано примерно %d."

#: ../duplicity/dup_main.py:1416
msgid "Unable to get max open files."
msgstr "Не удалось узнать максимальное количество открытых файлов."

#: ../duplicity/dup_main.py:1421
#, python-format
msgid "Max open files of %s is too low, should be >= 1024.\n"
"Use 'ulimit -n 1024' or higher to correct.\n"
msgstr "Максимальное количество открытых файлов %s слишком мало, Должно быть >= 1024.\n"
"Используйте 'ulimit -n 1024' или выше, чтобы исправить.\n"

#: ../duplicity/dup_main.py:1477
msgid "RESTART: The first volume failed to upload before termination.\n"
"         Restart is impossible...starting backup from beginning."
msgstr "ПЕРЕЗАПУСК: Ошибка выгрузки первого тома перед завершением работы.\n"
"         Перезапуск невозможен...выполнение резервного копирования с начала."

#: ../duplicity/dup_main.py:1487
#, python-format
msgid "RESTART: Volumes %d to %d failed to upload before termination.\n"
"         Restarting backup at volume %d."
msgstr "ПЕРЕЗАПУСК: Ошибка выгрузки томов %d дo %d перед завершением работы.\n"
"         Перезапуск резервного копирования в томе %d."

#: ../duplicity/dup_main.py:1498
#, python-format
msgid "RESTART: Impossible backup state: manifest has %d vols, remote has %d vols.\n"
"         Restart is impossible ... duplicity will clean off the last partial\n"
"         backup then restart the backup from the beginning."
msgstr "ПЕРЕЗАПУСК: Невозможное состояние резервной копии: манифест содержит %d томов, удалённый содержит %d томов.\n"
"         Перезапуск невозможен ... duplicity произведёт очистку последней части\n"
"         резервной копии, затем запустит резервное копирования сначала."

#: ../duplicity/dup_main.py:1523
msgid "PYTHONOPTIMIZE in the environment causes duplicity to fail to\n"
"recognize its own backups.  Please remove PYTHONOPTIMIZE from\n"
"the environment and rerun the backup.\n\n"
"See https://bugs.launchpad.net/duplicity/+bug/931175\n"
msgstr ""

#: ../duplicity/dup_main.py:1549
#, python-format
msgid "Acquiring lockfile %s"
msgstr ""

#: ../duplicity/dup_main.py:1609
#, python-brace-format
msgid "Last {action} backup left a partial set, restarting."
msgstr ""

#: ../duplicity/dup_main.py:1613
#, python-brace-format
msgid "Cleaning up previous partial {action} backup set, restarting."
msgstr ""

#: ../duplicity/dup_main.py:1627
msgid "Last full backup date: none"
msgstr "Время последней полной резервной копии: нету"

#: ../duplicity/dup_main.py:1634
msgid "Last full backup is too old, forcing full backup"
msgstr "Последняя полная резервная копия слишком старая, будет сделана полная резервная копия"

#: ../duplicity/dup_main.py:1690
msgid "When using symmetric encryption, the signing passphrase must equal the encryption passphrase."
msgstr "При использовании симметричного шифрования кодовая фраза для подписи должна совпадать с кодовой фразой для шифрования."

#: ../duplicity/asyncscheduler.py:259
#, python-format
msgid "task execution done (success: %s)"
msgstr "завершено выполнение задачи (успех: %s)"

#: ../duplicity/gpginterface.py:694
#, python-brace-format
msgid "GPG process {process.pid} terminated before wait()"
msgstr ""

#: ../duplicity/robust.py:84
#, python-format
msgid "Error listing directory %s"
msgstr "Ошибка перечня каталога %s"

#: ../duplicity/dup_collections.py:200 ../duplicity/dup_collections.py:209
#, python-format
msgid "BackupSet.delete: missing %s"
msgstr ""

#: ../duplicity/dup_collections.py:235
msgid "Fatal Error: No manifests found for most recent backup"
msgstr "Критическая ошибка: отсутствуют манифесты для недавней резервной копии"

#: ../duplicity/dup_collections.py:248
msgid "Fatal Error: Remote manifest does not match local one.  Either the remote backup set or the local archive directory has been corrupted."
msgstr "Критическая ошибка: Удалённый манифест не соответствует локальному. Неисправен удалённый набор резервного копирования или папка локального архива."

#: ../duplicity/dup_collections.py:256
#, python-format
msgid "Error processing remote manifest (%s): %s"
msgstr ""

#: ../duplicity/dup_collections.py:265
msgid "Fatal Error: Neither remote nor local manifest is readable."
msgstr "Критическая ошибка: Нет доступа к чтению удалённого и локального манифеста."

#: ../duplicity/dup_collections.py:276
#, python-format
msgid "Processing local manifest %s (%s)"
msgstr ""

#: ../duplicity/dup_collections.py:291
msgid "Error processing remote file ({os.fsdecode(remote_file)}): {util.uexc(message)}"
msgstr ""

#: ../duplicity/dup_collections.py:293
msgid "Processing remote file {os.fsdecode(remote_file)} ({len(remote_file_buffer)})"
msgstr ""

#: ../duplicity/dup_collections.py:311
msgid "No Jsonstat file found, return enmty."
msgstr ""

#: ../duplicity/dup_collections.py:404
msgid "Preferring Backupset over previous one!"
msgstr "Предпочтение набора резервного копирования вместо предыдущего!"

#: ../duplicity/dup_collections.py:408
#, python-format
msgid "Ignoring incremental Backupset (start_time: %s; needed: %s)"
msgstr "Пропуск инкрементального  набора резервного копирования (время_запуска: %s; необходимо: %s)"

#: ../duplicity/dup_collections.py:417
#, python-format
msgid "Added incremental Backupset (start_time: %s / end_time: %s)"
msgstr "Добавлена пошаговая резервная копия (время_начала: %s / время_конца: %s)"

#: ../duplicity/dup_collections.py:490
msgid "Chain start time: "
msgstr "Цепочка начата: "

#: ../duplicity/dup_collections.py:491
msgid "Chain end time: "
msgstr "Цепочка завершена: "

#: ../duplicity/dup_collections.py:492
#, python-format
msgid "Number of contained backup sets: %d"
msgstr "Количество содержащихся наборов резервного копирования: %d"

#: ../duplicity/dup_collections.py:493
#, python-format
msgid "Total number of contained volumes: %d"
msgstr "Общее число содержащихся томов: %d"

#: ../duplicity/dup_collections.py:494 ../duplicity/dup_collections.py:1308
msgid "Type of backup set:"
msgstr "Тип резервной копии:"

#: ../duplicity/dup_collections.py:494 ../duplicity/dup_collections.py:1308
msgid "Time:"
msgstr "Время:"

#: ../duplicity/dup_collections.py:494
msgid "Num volumes:"
msgstr "Число томов:"

#: ../duplicity/dup_collections.py:499 ../duplicity/dup_collections.py:1315
msgid "Full"
msgstr "Полная"

#: ../duplicity/dup_collections.py:502 ../duplicity/dup_collections.py:1317
msgid "Incremental"
msgstr "Пошаговая"

#: ../duplicity/dup_collections.py:563
msgid "local"
msgstr "Локальная"

#: ../duplicity/dup_collections.py:726
msgid "Collection Status"
msgstr "Состояние сбора"

#: ../duplicity/dup_collections.py:728
#, python-format
msgid "Connecting with backend: %s"
msgstr "Соединение с внутренним интерфейсом: %s"

#: ../duplicity/dup_collections.py:729
#, python-format
msgid "Archive dir: %s"
msgstr "Папка архива: %s"

#: ../duplicity/dup_collections.py:732
#, python-format
msgid "Found %d secondary backup chain(s)."
msgstr ""

#: ../duplicity/dup_collections.py:734
#, python-format
msgid "Secondary chain %d of %d:"
msgstr "Вторичная цепочка %d из %d:"

#: ../duplicity/dup_collections.py:739
msgid "Found primary backup chain with matching signature chain:"
msgstr "Найдена первичная цепочка резервного копирования с соответствующей цепочкой подписи:"

#: ../duplicity/dup_collections.py:742
msgid "No backup chains with active signatures found"
msgstr "Отсутствуют цепочки резервного копирования с найденными, задействованными подписями"

#: ../duplicity/dup_collections.py:745
#, python-format
msgid "Also found %d backup set(s) not part of any chain,"
msgstr ""

#: ../duplicity/dup_collections.py:746
#, python-format
msgid "and %d incomplete backup set(s)."
msgstr ""

#. "cleanup" is a hard-coded command, so do not translate it
#: ../duplicity/dup_collections.py:748
msgid "These may be deleted by running duplicity with the \"cleanup\" command."
msgstr "Это может быть удалено с помощью запуска duplicity с командой \"cleanup\"."

#: ../duplicity/dup_collections.py:750
msgid "No orphaned or incomplete backup sets found."
msgstr "Отсутствуют изолированные или неполные наборы резервного копирования."

#: ../duplicity/dup_collections.py:766
#, python-format
msgid "%d file(s) exists on backend"
msgstr ""

#: ../duplicity/dup_collections.py:772
#, python-format
msgid "%d file exists in cache"
msgid_plural "%d files exist in cache"
msgstr[0] ""
msgstr[1] ""
msgstr[2] ""
msgstr[3] ""

#: ../duplicity/dup_collections.py:831
msgid "Warning, discarding last backup set, because of missing signature file."
msgstr "Внимание, отозван последний набор резервного копирования, в связи с отсутствием файла подписи."

#: ../duplicity/dup_collections.py:854
msgid "Warning, found the following local orphaned signature file(s):"
msgstr ""

#: ../duplicity/dup_collections.py:862
msgid "Warning, found the following remote orphaned signature file(s):"
msgstr ""

#: ../duplicity/dup_collections.py:870
msgid "Warning, found signatures but no corresponding backup files"
msgstr "Внимание, найдены подписи, которые не соответствуют с файлами резервной копии"

#: ../duplicity/dup_collections.py:876
msgid "Warning, found incomplete backup sets, probably left from aborted session"
msgstr "Внимание, обнаружены незавершённые наборы резервных копий, возможно они остались от прерванного сеанса"

#: ../duplicity/dup_collections.py:882
msgid "Warning, found the following orphaned backup file(s):"
msgstr ""

#: ../duplicity/dup_collections.py:897
#, python-format
msgid "Extracting backup chains from list of files: %s"
msgstr "Извлечение цепочек резервного копирования из списка файлов: %s"

#: ../duplicity/dup_collections.py:908
#, python-format
msgid "File %s is part of known set"
msgstr "Файл %s является частью известного набора"

#: ../duplicity/dup_collections.py:911
#, python-format
msgid "File %s is not part of a known set; creating new set"
msgstr "Файл %s не является частью известного набора; создаётся новый набор"

#: ../duplicity/dup_collections.py:916
#, python-format
msgid "Ignoring file (rejected by backup set) '%s'"
msgstr "Пропуск файла (отклонено набором резервного копирования) '%s'"

#: ../duplicity/dup_collections.py:932
#, python-format
msgid "Found backup chain %s"
msgstr "Найдена резервная копия %s"

#: ../duplicity/dup_collections.py:937
#, python-format
msgid "Added set %s to pre-existing chain %s"
msgstr "Добавление набора %s для ранее существующей цепочки %s"

#: ../duplicity/dup_collections.py:940
#, python-format
msgid "Found orphaned set %s"
msgstr "Обнаружен изолированный набор %s"

#: ../duplicity/dup_collections.py:1088
#, python-format
msgid "No signature chain for the requested time. Using oldest available chain, starting at time %s."
msgstr ""

#: ../duplicity/dup_collections.py:1306
#, python-format
msgid "File: %s"
msgstr "Файл: %s"

#: ../duplicity/dup_collections.py:1307
#, python-format
msgid "Total number of backup: %d"
msgstr "Общее количество резервного копирования: %d"

#: ../duplicity/dup_collections.py:1308 ../duplicity/dup_collections.py:1344
msgid "Type of file change:"
msgstr "Тип изменения файла:"

#: ../duplicity/dup_collections.py:1342
#, python-format
msgid " Backup set time: %s"
msgstr ""

#: ../duplicity/dup_collections.py:1343
#, python-format
msgid "Total number of changes: %d"
msgstr ""

#: ../duplicity/dup_collections.py:1344
msgid "File:"
msgstr ""

#: ../duplicity/patchdir.py:72 ../duplicity/patchdir.py:79
#, python-format
msgid "Patching %s"
msgstr "Внесение изменений в %s"

#: ../duplicity/patchdir.py:547
#, python-format
msgid "Error '%s' patching %s"
msgstr ""

#: ../duplicity/patchdir.py:624
#, python-format
msgid "Writing %s of type %s"
msgstr "Запись %s типа %s"

#: ../duplicity/selection.py:115
#, python-format
msgid "Skipping socket %s"
msgstr "Пропуск сокета %s"

#: ../duplicity/selection.py:121
#, python-format
msgid "Error initializing file %s"
msgstr "Ошибка инициализации файла %s"

#: ../duplicity/selection.py:127 ../duplicity/selection.py:167
#: ../duplicity/selection.py:615
#, python-format
msgid "Error accessing possibly locked file %s"
msgstr "Ошибка доступа к возможно заблокированному файлу %s"

#: ../duplicity/selection.py:182
#, python-format
msgid "Warning: base %s doesn't exist, continuing"
msgstr "Внимание: база %s не существует, выполняется продолжение"

#: ../duplicity/selection.py:184 ../duplicity/selection.py:205
#: ../duplicity/selection.py:208
#, python-format
msgid "Selecting %s"
msgstr "Выбор %s"

#: ../duplicity/selection.py:263
#, python-format
msgid "                The last file selection option is the filter option %s, which will have no\n"
"                effect as there are no subsequent file selection options. Exiting because\n"
"                this probably isn't what you meant."
msgstr ""

#: ../duplicity/selection.py:278
#, python-format
msgid "                Only these filter mode options were specified:\n"
"                    %s\n"
"                Case sensitive globbing is the default behaviour and so this has no effect.\n"
"                Exiting because this probably isn't what you meant."
msgstr ""

#: ../duplicity/selection.py:346
#, python-format
msgid "                Fatal Error: The file specification\n"
"                    %s\n"
"                cannot match any files in the base directory\n"
"                    %s\n"
"                Useful file specifications begin with the base directory or some\n"
"                pattern (such as '**') which matches the base directory."
msgstr ""

#: ../duplicity/selection.py:360
#, python-format
msgid "Fatal Error while processing expression\n"
"%s"
msgstr "Критическая ошибка при обработке выражения\n"
"%s"

#: ../duplicity/selection.py:378
#, python-format
msgid "Reading files to backup from list %s"
msgstr ""

#: ../duplicity/selection.py:403
#, python-format
msgid "                Files-from list contains the absolute path:\n"
"                    %s\n"
"                All paths specified in a files-from list must be given relative to the backup\n"
"                source path."
msgstr ""

#: ../duplicity/selection.py:418
msgid "                Files-from list specified which contains no files, the backup will be empty as\n"
"                a result. Exiting as this probably isn't what you meant,"
msgstr ""

#: ../duplicity/selection.py:435
#, python-format
msgid "                Last selection expression:\n"
"                    %s\n"
"                only specifies that files be included.  Because the default is to\n"
"                include all files, the expression is redundant.  Exiting because this\n"
"                probably isn't what you meant."
msgstr ""

#: ../duplicity/selection.py:497
#, python-format
msgid "Reading %s filelist %s"
msgstr ""

#: ../duplicity/selection.py:538
#, python-format
msgid "Error compiling regular expression %s"
msgstr "Ошибка компилирования регулярного выражения %s"

#: ../duplicity/lazy.py:349
#, python-format
msgid "Warning: oldindex %s >= newindex %s"
msgstr "Внимание: старый индекс %s >= нового индекса %s"

#: ../duplicity/lazy.py:424
#, python-format
msgid "Error '%s' processing %s"
msgstr "Ошибка '%s' при обработке %s"

#: ../duplicity/lazy.py:436
#, python-format
msgid "Skipping %s because of previous error"
msgstr "Пропуск %s из-за предыдущей ошибки"

#: ../duplicity/path.py:109
#, python-format
msgid "Warning: %s invalid devnums (0x%X), treating as (0, 0)."
msgstr ""

#: ../duplicity/path.py:239 ../duplicity/path.py:299
#, python-format
msgid "Warning: %s has negative mtime, treating as 0."
msgstr "Внимание: у %s отрицательное mtime, принимается равным 0."

#: ../duplicity/path.py:372
#, python-format
msgid "New file %s"
msgstr "Новый файл %s"

#: ../duplicity/path.py:375
#, python-format
msgid "File %s is missing"
msgstr "Файл %s отсутствует"

#: ../duplicity/path.py:378
#, python-format
msgid "File %%s has type %s, expected %s"
msgstr "Файл %%s относится к типу %s, а ожидался %s"

#: ../duplicity/path.py:383 ../duplicity/path.py:412
#, python-format
msgid "File %%s has permissions %s, expected %s"
msgstr "Файл %%s имеет разрешения %s, а ожидалось %s"

#: ../duplicity/path.py:389
#, python-format
msgid "File %%s has mtime %s, expected %s"
msgstr "Файл %%s имеет mtime %s, а ожидалось %s"

#: ../duplicity/path.py:400
#, python-format
msgid "Data for file %s is different"
msgstr "Данные для файла %s отличаются"

#: ../duplicity/path.py:408
#, python-format
msgid "Symlink %%s points to %s, expected %s"
msgstr "Символическая ссылка %%s указывает на %s, а ожидалось %s"

#: ../duplicity/path.py:415
#, python-format
msgid "Device file %%s has numbers %s, expected %s"
msgstr "Файл устройства %%s содержит номера %s, а ожидались %s"

#: ../duplicity/path.py:605
#, python-format
msgid "Making directory %s"
msgstr "Создаётся каталог %s"

#: ../duplicity/path.py:615
#, python-format
msgid "Deleting %s"
msgstr "Удаляется %s"

#: ../duplicity/path.py:624
#, python-format
msgid "Touching %s"
msgstr ""

#: ../duplicity/path.py:632
#, python-format
msgid "Deleting tree %s"
msgstr "Удаление дерева %s"

#: ../duplicity/cli_util.py:48
msgid "Enter 'duplicity --help' for help screen."
msgstr ""

#: ../duplicity/cli_util.py:127
msgid "Running in 'ignore errors' mode due to --ignore-errors.\n"
"Please reconsider if this was not intended"
msgstr ""

#: ../duplicity/cli_util.py:139
msgid "Use of the --asynchronous-upload option is experimental and not safe for production! There are reported cases of undetected data loss during upload. Be aware and periodically verify your backups to be safe."
msgstr ""

#: ../duplicity/cli_util.py:152
msgid "'{val}' is not an int: {str(e)}"
msgstr ""

#: ../duplicity/cli_util.py:166
#, python-brace-format
msgid "'{val} is not a single character."
msgstr ""

#: ../duplicity/cli_util.py:193
#, python-brace-format
msgid "Source should be pathname, not url.  Got '{val}' instead."
msgstr ""

#: ../duplicity/cli_util.py:195
#, python-brace-format
msgid "Argument source_path '{val}' does not exist."
msgstr ""

#: ../duplicity/cli_util.py:201
#, python-brace-format
msgid "Source should be url, not directory.  Got '{val}' instead."
msgstr ""

#: ../duplicity/cli_util.py:207
#, python-brace-format
msgid "Target should be directory, not url.  Got '{val}' instead."
msgstr ""

#: ../duplicity/cli_util.py:212
msgid "Unable to create target dir '{val}': {str(e)}"
msgstr ""

#: ../duplicity/cli_util.py:218
#, python-brace-format
msgid "Target should be url, not directory.  Got '{val}' instead."
msgstr ""

#: ../duplicity/cli_util.py:263
msgid "Verbosity must be one of: digit [0-9], character [ewnid],\n"
"or word ['error', 'warning', 'notice', 'info', 'debug'].\n"
"The default is 3 (Notice).  It is strongly recommended\n"
"that verbosity level is set at 2 (Warning) or higher."
msgstr ""

#: ../duplicity/cli_util.py:399
#, python-brace-format
msgid "Specified archive directory '{archive_dir_path.uc_name}' is not a directory"
msgstr ""

#: ../duplicity/cli_util.py:408
msgid "Encrypt key should be an 8, 16, or 40 character hex string, like 'AA0E73D2'.\n"
msgstr ""

#: ../duplicity/cli_util.py:428
msgid "Hidden dncrypt key should be an 8, 16, or 40 character hex string, like 'AA0E73D2'.\n"
msgstr ""

#: ../duplicity/cli_util.py:442
msgid "Sign key should be an 8, 16, or 40 character hex string, like 'AA0E73D2'.\n"
msgstr ""

#: ../duplicity/argparse311.py:291
msgid "usage: "
msgstr ""

#: ../duplicity/argparse311.py:761
#, python-format
msgid "argument %(argument_name)s: %(message)s"
msgstr ""

#: ../duplicity/argparse311.py:870
msgid ".__call__() not defined"
msgstr ""

#: ../duplicity/argparse311.py:1115
#, python-format
msgid "conflicting subparser: %s"
msgstr ""

#: ../duplicity/argparse311.py:1118
#, python-format
msgid "conflicting subparser alias: %s"
msgstr ""

#: ../duplicity/argparse311.py:1152
#, python-format
msgid "unknown parser %(parser_name)r (choices: %(choices)s)"
msgstr ""

#: ../duplicity/argparse311.py:1215
#, python-format
msgid "argument \"-\" with mode %r"
msgstr ""

#: ../duplicity/argparse311.py:1223
#, python-format
msgid "can't open '%(filename)s': %(error)s"
msgstr ""

#: ../duplicity/argparse311.py:1427
#, python-format
msgid "cannot merge actions - two groups are named %r"
msgstr ""

#: ../duplicity/argparse311.py:1462
msgid "'required' is an invalid argument for positionals"
msgstr ""

#: ../duplicity/argparse311.py:1483
#, python-format
msgid "invalid option string %(option)r: must start with a character %(prefix_chars)r"
msgstr ""

#: ../duplicity/argparse311.py:1500
#, python-format
msgid "dest= is required for options like %r"
msgstr ""

#: ../duplicity/argparse311.py:1517
#, python-format
msgid "invalid conflict_resolution value: %r"
msgstr ""

#: ../duplicity/argparse311.py:1534
#, python-format
msgid "conflicting option string: %s"
msgid_plural "conflicting option strings: %s"
msgstr[0] ""
msgstr[1] ""
msgstr[2] ""
msgstr[3] ""

#: ../duplicity/argparse311.py:1595
msgid "mutually exclusive arguments must be optional"
msgstr ""

#: ../duplicity/argparse311.py:1670
msgid "positional arguments"
msgstr ""

#: ../duplicity/argparse311.py:1689
msgid "show this help message and exit"
msgstr ""

#: ../duplicity/argparse311.py:1721
msgid "cannot have multiple subparser arguments"
msgstr ""

#: ../duplicity/argparse311.py:1769 ../duplicity/argparse311.py:2264
#, python-format
msgid "unrecognized arguments: %s"
msgstr ""

#: ../duplicity/argparse311.py:1868
#, python-format
msgid "not allowed with argument %s"
msgstr ""

#: ../duplicity/argparse311.py:1912 ../duplicity/argparse311.py:1926
#, python-format
msgid "ignored explicit argument %r"
msgstr ""

#: ../duplicity/argparse311.py:2030
#, python-format
msgid "the following arguments are required: %s"
msgstr ""

#: ../duplicity/argparse311.py:2042
#, python-format
msgid "one of the arguments %s is required"
msgstr ""

#: ../duplicity/argparse311.py:2083
msgid "expected one argument"
msgstr ""

#: ../duplicity/argparse311.py:2084
msgid "expected at most one argument"
msgstr ""

#: ../duplicity/argparse311.py:2085
msgid "expected at least one argument"
msgstr ""

#: ../duplicity/argparse311.py:2089
#, python-format
msgid "expected %s argument"
msgid_plural "expected %s arguments"
msgstr[0] ""
msgstr[1] ""
msgstr[2] ""
msgstr[3] ""

#: ../duplicity/argparse311.py:2143
#, python-format
msgid "ambiguous option: %(option)s could match %(matches)s"
msgstr ""

#: ../duplicity/argparse311.py:2207
#, python-format
msgid "unexpected option string: %s"
msgstr ""

#: ../duplicity/argparse311.py:2402
#, python-format
msgid "%r is not callable"
msgstr ""

#: ../duplicity/argparse311.py:2419
#, python-format
msgid "invalid %(type)s value: %(value)r"
msgstr ""

#: ../duplicity/argparse311.py:2429
#, python-format
msgid "invalid choice: %(value)r (choose from %(choices)s)"
msgstr ""

#: ../duplicity/argparse311.py:2505
#, python-format
msgid "%(prog)s: error: %(message)s\n"
msgstr ""

